### PR TITLE
 Fix stripping of OSX libraries in CMake target files (fixes #170) 

### LINKED ISSUE #170: Incorrect regex in OSX build
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

As stated in https://github.com/conda-forge/gdal-feedstock/pull/741#issuecomment-1478814528,

> Regex at https://github.com/conda-forge/libnetcdf-feedstock/pull/169 seems wrong

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

### PR DESCRIPTION
**Pull request by rouault**
Demo (on Linux...)
```
$ echo /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/libpthread.dylib | sed -E "s#/Applications/Xcode_[0-9]*.[0-9]*.[0-9]*.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX[0-9]*.[0-9]*.sdk/usr/lib/lib([a-zA-Z0-9]*).(dylib|tbd)#\1#g"
pthread
$ echo /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/libpthread.tbd | sed -E "s#/Applications/Xcode_[0-9]*.[0-9]*.[0-9]*.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX[0-9]*.[0-9]*.sdk/usr/lib/lib([a-zA-Z0-9]*).(dylib|tbd)#\1#g"
pthread
```

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

closes #170

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Review by xylar — APPROVED** [review]

**Comment by ihnorton** [comment]
LGTM. On mac:
```
echo /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/libpthread.dylib | sed -E "s#/Applications/Xcode_[0-9]*.[0-9]*.[0-9]*.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX[0-9]*.[0-9]*.sdk/usr/lib/lib([a-zA-Z0-9]*).(dylib|tbd)#\1#g"
pthread
```

**Comment by rouault** [comment]
hum, there is still something wrong:
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/677547/logs/88:
```
2023-03-22T12:22:34.2398150Z + cat /Users/runner/miniforge3/conda-bld/libnetcdf_1679487073963/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/cmake/netCDF/netCDFTargets.cmake
[...]
2023-03-22T12:22:34.2483380Z   INTERFACE_LINK_LIBRARIES "$PREFIX/lib/libmfhdf.dylib;$PREFIX/lib/libdf.dylib;$PREFIX/lib/libhdf5_hl.dylib;$PREFIX/lib/libhdf5.dylib;$PREFIX/lib/libcrypto.dylib;$PREFIX/lib/libcurl.dylib;pthreadylib;$PREFIX/lib/libsz.dylib;$PREFIX/lib/libz.dylib;dlylib;mylib;$PREFIX/lib/libzstd.dylib;$PREFIX/lib/libbz2.dylib;$PREFIX/lib/libxml2.dylib"
```
I'm going to change to have 2 separate sed invokations...

**Comment by rouault** [comment]
This time, we should good to go:

osx x86_64:
2023-03-22T13:09:03.7805560Z   INTERFACE_LINK_LIBRARIES "$PREFIX/lib/libmfhdf.dylib;$PREFIX/lib/libdf.dylib;$PREFIX/lib/libhdf5_hl.dylib;$PREFIX/lib/libhdf5.dylib;$PREFIX/lib/libcrypto.dylib;$PREFIX/lib/libcurl.dylib;pthread;$PREFIX/lib/libsz.dylib;$PREFIX/lib/libz.dylib;dl;m;$PREFIX/lib/libzstd.dylib;$PREFIX/lib/libbz2.dylib;$PREFIX/lib/libxml2.dylib"

osx arm64:
2023-03-22T13:07:48.3206310Z   INTERFACE_LINK_LIBRARIES "$PREFIX/lib/libmfhdf.dylib;$PREFIX/lib/libdf.dylib;$PREFIX/lib/libhdf5_hl.dylib;$PREFIX/lib/libhdf5.dylib;$PREFIX/lib/libcrypto.dylib;$PREFIX/lib/libcurl.dylib;pthread;$PREFIX/lib/libsz.dylib;$PREFIX/lib/libz.dylib;dl;m;$PREFIX/lib/libzstd.dylib;$PREFIX/lib/libbz2.dylib;$PREFIX/lib/libxml2.dylib"

linux:
2023-03-22T13:05:46.9304923Z   INTERFACE_LINK_LIBRARIES "dl;$PREFIX/lib/libmfhdf.so;$PREFIX/lib/libdf.so;$PREFIX/lib/libhdf5_hl.so;$PREFIX/lib/libhdf5.so;$PREFIX/lib/libcrypto.so;$PREFIX/lib/libcurl.so;rt;pthread;$PREFIX/lib/libsz.so;$PREFIX/lib/libz.so;dl;m;$PREFIX/lib/libzstd.so;$PREFIX/lib/libbz2.so;$PREFIX/lib/libxml2.so"

**Comment by xylar** [comment]
Thanks very much @rouault!

**Pull request merged**
