### PR TITLE
Update hdf pin to the latest hdf5 version...

### PR DESCRIPTION
**Pull request by ocefpaf**
... and add some extra DAP tests.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Looks like Windows is not happy with latest `hdf5` 😒

**Comment by qwhelan** [comment]
@ocefpaf Found this in some other ```bld.bat```s:

    set HDF5_DIR=%LIBRARY_PREFIX%

Might be worth a shot to see if that gives ```cmake``` enough info.

**Comment by ocefpaf** [comment]
Worth trying. I am only on mobile phone for a while. (reinstalling my
OSes). Can you try that in your PR?

**Comment by qwhelan** [comment]
Sure, just pushed it. There's a fair amount of CI backlog at the moment so might be a while before we know.

**Comment by ocefpaf** [comment]
Thanks! (Don't worry about the CIs backlog, it may take a few days until we
finish the move to the latest hdf5.)

**Pull request closed without merging**
