### PR TITLE
V4.6.3

### PR DESCRIPTION
**Pull request by ocefpaf**
Alternative for #71

### CODE REVIEW

**Comment by ocefpaf** [comment]
Even though is this passing I'm pulling the packages here b/c the soname changed and this breaks our stack. I'll update the pinning first and then we can re-add `4.6.3`.

**Comment by ocefpaf** [comment]
BTW, `4.6.3` should actually be `4.7.0` due to the rename.

**Comment by beckermr** [comment]
We should take this up w/ upstream, right?

**Comment by ocefpaf** [comment]
> We should take this up w/ upstream, right?

If upstream is worried about ABI compatibility and semver, yes. Otherwise I would not bother, it will be just noise for them.

**Pull request merged**
