### PR TITLE
Patch to install ncexternl.h in v 4.7.2

### PR DESCRIPTION
**Pull request by xylar**
This file is imported in netcdf_par.h and is needed by parallel builds of netcdf4 (see https://github.com/conda-forge/netcdf4-feedstock/pull/95)

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by dopplershift** [comment]
Just a heads up, I think this is fixed in the forthcoming 4.7.3, which is already in #90 .

**Comment by xylar** [comment]
I realize, given the current pinning of libnetcdf, I'll probably need to patch 4.7.1 as well.

**Comment by xylar** [comment]
@dopplershift, I noticed that, that's great!  But the current pinning is libnetcdf 4.7.1 so the patch is probably still needed in both 4.7.2 and 4.7.1 as well until the pinning is migrated.

**Comment by kmuehlbauer** [comment]
@xylar Do you have any idea what's wrong wrong with the `openmpi` builds? #90 was failing too, I restarted 90 min ago, but same behaviour. At some point the output console breaks somehow.

**Comment by xylar** [comment]
@kmuehlbauer, no, no idea.  I'm working on a train right now so I gave up on trying to do a local openmpi build on my laptop and decided to let CI give it a go.  Once I'm back to "civilization", I can give it another try locally and see if I can reproduce the problem.

**Comment by kmuehlbauer** [comment]
@xylar That's the same location as in #90. I extended my comment with these lines.

`openmpi` was updated 10 days ago to version 4.0.2. Not sure, if this is related.

**Comment by xylar** [comment]
It doesn't look like conda-smithy is pinning the `openmpi` or `mpich` versions at all:
https://github.com/conda-forge/libnetcdf-feedstock/blob/master/.ci_support/linux_mpiopenmpi.yaml#L19-L20

This is odd, given that there are pinnings:
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml#L528-L529

**Comment by kmuehlbauer** [comment]
@xylar This is beyond my current conda-fu, unfortunately...

**Comment by kmuehlbauer** [comment]
@xylar search-fu is still there: https://github.com/open-mpi/ompi/issues/7109

**Comment by xylar** [comment]
@kmuehlbauer, nice searching!  Does this mean we should patch our openmpi feedstock?  Probably so...

I'm trying to do something with `esmf` and `moab`, and I keep getting drawn further and further upstream in the dependency tree trying to get things working.  Going to `openmpi` seems ridiculous but I'll give it a go...

**Comment by kmuehlbauer** [comment]
Yeah, either waiting for `openmpi=4.0.3` or patching...

**Comment by xylar** [comment]
Okay, a patch seems preferable. A new openmpi release will require rebuilding a lot more packages.

**Comment by xylar** [comment]
I tested this with a local build of https://github.com/conda-forge/openmpi-feedstock/pull/52 and the problem does seem to be fix.

**Comment by kmuehlbauer** [comment]
@xylar As #90 is not yet due, your #91 and #92 could be merged before #90.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge/libnetcdf, I believe this is ready to merge.  Please let me know if you have concerns.

**Comment by xylar** [comment]
Actually, let's merge #92 first and then this one.  That way I don't have to do another PR to switch back to 4.7.2.

**Pull request merged**
