### PR TITLE
add osx_arm64

### PR DESCRIPTION
**Pull request by matthiasdiener**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
@conda-forge-admin restart CI

**Comment by matthiasdiener** [comment]
@conda-forge-admin restart CI

**Comment by matthiasdiener** [comment]
The Open MPI build fails with 

```
-- The C compiler identification is unknown
-- The CXX compiler identification is Clang 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: $PREFIX/bin/mpicc
-- Check for working C compiler: $PREFIX/bin/mpicc - broken
CMake Error at /Users/runner/miniforge3/conda-bld/libnetcdf_1618608415008/_build_env/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/Users/runner/miniforge3/conda-bld/libnetcdf_1618608415008/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/mpicc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/runner/miniforge3/conda-bld/libnetcdf_1618608415008/work/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/Users/runner/miniforge3/conda-bld/libnetcdf_1618608415008/_build_env/bin/make -f Makefile cmTC_564f8/fast && /Users/runner/miniforge3/conda-bld/libnetcdf_1618608415008/_build_env/bin/make  -f CMakeFiles/cmTC_564f8.dir/build.make CMakeFiles/cmTC_564f8.dir/build
    make[1]: Entering directory '/Users/runner/miniforge3/conda-bld/libnetcdf_1618608415008/work/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_564f8.dir/testCCompiler.c.o
    /Users/runner/miniforge3/conda-bld/libnetcdf_1618608415008/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/mpicc   -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/runner/miniforge3/conda-bld/libnetcdf_1618608415008/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/libnetcdf_1618608415008/work=/usr/local/src/conda/libnetcdf-4.8.0 -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/libnetcdf_1618608415008/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold=/usr/local/src/conda-prefix  -o CMakeFiles/cmTC_564f8.dir/testCCompiler.c.o -c /Users/runner/miniforge3/conda-bld/libnetcdf_1618608415008/work/CMakeFiles/CMakeTmp/testCCompiler.c
    make[1]: /Users/runner/miniforge3/conda-bld/libnetcdf_1618608415008/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/mpicc: Bad CPU type in executable
    make[1]: *** [CMakeFiles/cmTC_564f8.dir/build.make:78: CMakeFiles/cmTC_564f8.dir/testCCompiler.c.o] Error 127
    make[1]: Leaving directory '/Users/runner/miniforge3/conda-bld/libnetcdf_1618608415008/work/CMakeFiles/CMakeTmp'
    make: *** [Makefile:127: cmTC_564f8/fast] Error 2
```

Mpich/nompi are building fine.

@conda-forge/libnetcdf @isuruf Do you have any idea what the issue could be?

**Comment by isuruf** [comment]
See #122

**Comment by matthiasdiener** [comment]
Closed in favor of #122.

**Pull request closed without merging**
