### PR TITLE
[NO MERGE] Testing upstream fixes for HDF5 detection

### PR DESCRIPTION
**Pull request by dopplershift**
Testing potential upstream CMake fixes so that hopefully the next release is easier.

cc @WardF

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dopplershift** [comment]
See Unidata/netcdf-c#2095.

**Comment by WardF** [comment]
@dopplershift It looks like the most recent checks failed for a [new/unrelated reason](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=369727&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f).  Could we restart them and see if the issue persists or if it was a one-off thing?

**Comment by WardF** [comment]
I've fixed the appveyor issue over on the netcdf-c repo; once we figure out the windows cmake issue here, I'll get everything merged back in together.

**Comment by dopplershift** [comment]
@WardF the failure was actually due to the patch failing to apply. I've changed how I'm generating it to now baseline against the v4.8.1 branch rather than master--plus a couple manual edits. I'd expect this one to work better.

**Comment by WardF** [comment]
@dopplershift Thanks! I appreciate your help in tracking this down.  It looks like all the tests are passing, is there anything else on your end before I can check this off and merge the PR back over at `Unidata/netcdf-c`?

**Comment by dopplershift** [comment]
I'm just waiting to see Drone pass (aarch64) to call this complete.

**Comment by dopplershift** [comment]
Alright, hopefully this should make getting 4.8.2 built upon release much easier.

**Pull request closed without merging**
