### PR TITLE
Aarch without hdf4

### PR DESCRIPTION
**Pull request by hmaarrfk**
dear maintainers.
I'm proposing that we remove the hard dependency on HDF4 on little endian architectures.

I found that it is likely seriously broken seeing as Debian has packaged it with some large patches.

seeing as it is pretty old, I'm wondering how many of your users depend on HDF4 datasets. is it worthwhile to patch up HDF4?

all existing architectures maintain their current functionality.
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@msarahan it seems a dataset is now missing.

you left a comment to contact you. could you please find a way to fixup the build right

**Comment by ocefpaf** [comment]
LGTM @hmaarrfk. Merge?

**Comment by hmaarrfk** [comment]
I'm not sure if we need to hear from msarahan regarding the skipped tests.

I would also like to close the boys PR for HDF4 so that the migration can continue.

**Comment by ocefpaf** [comment]
> I'm not sure if we need to hear from msarahan regarding the skipped tests.

No need. I guess we even skipped those tests on `master` too.

> I would also like to close the boys PR for HDF4 so that the migration can continue.

Yes please. Sorry for dropping the ball. Do you mind rebasing? If not I can try to re-issue this PR.

**Comment by hmaarrfk** [comment]
hmm, ok. rebased. PR much cleaner now. thanks

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
Travis seems to be close to running out of space ;)

**Pull request merged**
