### PR TITLE
Backport fix for Unidata/netcdf-c#2674

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This hopefully fixes the issue of overly abundant HDF5-DIAG messages that has plagued a number of downstream projects.

### CODE REVIEW

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
The build problem on Osx is due to a mistaken detection of `clock_gettime`, which is in fact not available on Osx. This is correctly detected on other Osx builds and on earlier Osx-Mpich builds. My suspicion is that the use of Cmake's [`CHECK_FUNCTION_EXISTS`](https://cmake.org/cmake/help/latest/module/CheckFunctionExists.html) picks up a possibly wrongly exported `clock_gettime` from an updated dependency in the Mpich branch of the dependency tree. From the Cmake docu:
> `check_function_exists()` only verifies linking, it does not verify that the function is declared in system headers.

As such the error is unrelated to this PR, but I'll try to address it.

**Review by kmuehlbauer — APPROVED** [review]
@zklaus Thanks for doing this! It would be great to get this in soon.

**Review by xylar — APPROVED** [review]
@zklaus, thanks for doing this.  It will be great to have you as a maintainer.

**Comment by xylar** [comment]
I'll merge in the next few hours unless anyone objects.

**Pull request merged**
