### PR TITLE
Use CMAKE_PREFIX_PATH

### LINKED ISSUE #101: hardwired lib paths in cmake config
on windows, netcdftargets.cmake contains hadwired paths to dependencies and it fails to build:
```
set_target_properties(netCDF::netcdf PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "D:/bld/libnetcdf_1587069359154/_h_env/Library/lib/mfhdf.lib;D:/bld/libnetcdf_1587069359154/_h_env/Library/lib/hdf.lib;hdf5-shared;hdf5_hl-shared;D:\\bld\\libnetcdf_1587069359154\\_h_env\\Library\\lib\\zlib.lib;D:/bld/libnetcdf_1587069359154/_h_env/Library/lib/libcurl.lib"
)
```

here is the error:
```
NMAKE : fatal error U1073: don't know how to make 'D:\bld\libnetcdf_1587069359154\_h_env\Library\lib\zlib.lib'
```

I guess this is because lib paths are manually given instead of letting cmake find them with CMAKE_PREFIX_PATH, take example from
https://github.com/conda-forge/nlopt-feedstock/blob/master/recipe/bld.bat

### PR DESCRIPTION
**Pull request by jschueller**
Dont path manually lib paths, let CMAKE_PREFIX_PATH do its job.
Manually setting lib paths with wrong slashes prevented the automatic replace for windows.
Closes #101 

@conda-forge-admin please rerender

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by jschueller** [comment]
The travis build seems broken

**Comment by xylar** [comment]
@conda-forge-admin please rerender

**Comment by jschueller** [comment]
I've been force-pushing twice already to rerun, maybe it can be ignored for now ?

**Comment by xylar** [comment]
> I've been force-pushing twice already to rerun, maybe it can be ignored for now ?

Rerendering was giving me trouble yesterday, too.  I just figured it would be the easiest way to restart CI if a rerender were still needed.  If not, one can close and reopen the PR (or make the bot do that) to make the CI restart.

**Comment by jschueller** [comment]
ok, it passes on Travis although we have one test failure on osx/mpi, must be a random error from parallelism.

**Comment by jschueller** [comment]
thanks for restarting, all good now!

**Comment by xylar** [comment]
@conda-forge/libnetcdf, would anyone else like to review? If so, please do so in the next day or so.

**Comment by beckermr** [comment]
Do the cmake changes mean this is now vendoring zlib and curl, or did setting the prefix make the build look in the right spot?

**Comment by jschueller** [comment]
It looks in the right spot

**Comment by xylar** [comment]
Okay, going to merge having heard nothing else.

**Comment by xylar** [comment]
Thanks @jschueller for this work!

**Pull request merged**
