### PR TITLE
[DO NOT MERGE] Dummy build

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
What do I do with this?

**Comment by djhoese** [comment]
@DennisHeimbigner The CI/checks being run can lead you to the build logs. You can click on "Details" to the right of the job and then click on the link to Azure from that page. That will bring you to something like:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=767053&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f

where the "Build recipe" task is the actual build/compiling log for the library and packaging it up.

I don't remember if there was something that was being looked for specifically in these logs.

**Comment by dopplershift** [comment]
@xylar Can you grab a few of the commits from #185 to add the test, turn on logging, etc.?

**Comment by xylar** [comment]
@dopplershift, I think it would be easier for you to make a dummy PR and do those things.  I would be happy to do that tomorrow but it's 10 pm my time and I'm calling it a day.

**Comment by ocefpaf** [comment]
> @dopplershift, I think it would be easier for you to make a dummy PR and do those things. I would be happy to do that tomorrow but it's 10 pm my time and I'm calling it a day.

No worries. I believe I got them all in the last commit here. Hopefully the logs and the artifacts will help us debug this.

**Comment by ocefpaf** [comment]
We need to pin to the older hdf5 now :-/

I'll do that early tomorrow if no one beats me to it.

**Comment by xylar** [comment]
I think I'm going to close this.  It won't be very helpful anymore, though we could resurrect it later.

**Pull request closed without merging**
