### PR TITLE
WIP: Split the static library

### PR DESCRIPTION
**Pull request by hmaarrfk**
Try to build the static library depending on the package name.

Closes https://github.com/conda-forge/libnetcdf-feedstock/issues/134

Challenges to address:
- [ ] the `nc-config` file is shared between the two. Do we want to include it in the static build?

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Sigh test.67 has been failing for me again. Any clue on what might be going on?
```
2022-01-18T22:46:26.0697172Z *** Testing: test.67 ; url=[cache][prefetch]https://remotetest.unidata.ucar.edu/dts/test.67
2022-01-18T22:46:26.0697572Z 41c41
2022-01-18T22:46:26.0697934Z <     0.589788025031098, 0.581683089463883, 0.573519986072457, 
2022-01-18T22:46:26.0698680Z ---
2022-01-18T22:46:26.0699125Z >     0.589788025031098, 0.581683089463884, 0.573519986072457, 
2022-01-18T22:46:26.0699518Z *** FAIL:  test.67
```
Seems like a rounding error. But I don't know how to skip that test specifically.

**Comment by hmaarrfk** [comment]
Asked upstream about the failures:
https://github.com/Unidata/netcdf-c/issues/2188

**Comment by ocefpaf** [comment]
> * the `nc-config` file is shared between the two. Do we want to include it in the static build?

Probably not. While it makes sense it would make this a bit difficult. Let's keep it only on the shared version of the lib for now.

**Comment by hmaarrfk** [comment]
@xylar 

I've done a few o these static/dynamic splits. I've learned:
1. I don't think anybody has complained that the static libraries disappeared from the standard package. Was anybody using them? Sometimes they were just "there by default" and nobody really asked for them.
2. They have many incompatibilities with different configuration files. it isn't really easy to ensure that the installations are compatible in 100% of the cases for static/dynamic splits.

For this reason, I'm really less excited about them. I would simply prefer to remove the static library and call it day for these large pacakges.

I'm not excited to take on the responsibility of the knock on effects at this moment that will arise from splitting the static library.

**Comment by xylar** [comment]
@hmaarrfk, I support your proposal to just drop the static library and see what the consequences are.  I would be happy to help deal with the downstream consequences.  I will be extremely busy for the next 2 weeks but could take that on in October.

I appreciate you getting the ball rolling here since this will give me a good idea how do proceed.

Once that has happened and we see what the consequences are, I'll try netcdf-fortran.

**Comment by hmaarrfk** [comment]
static library has been deleted.

**Pull request closed without merging**
