### PR TITLE
Create a build with hdf5 pinned to 1.10.2

### PR DESCRIPTION
**Pull request by xylar**
Set build to 200
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
After #59, an issue with netCDF4 not supporting cdf-5 (https://github.com/conda-forge/netcdf4-feedstock/issues/67)has been fixed!  However, there are a *lot* of conda-forge packages that still don't support hdf5 1.10.3 (notably h5py: https://github.com/conda-forge/h5py-feedstock/issues/41).  It would be very helpful to have a build of libnetcdf with the build fix in #59 and hdf5 1.10.2 while hdf5 1.10.3 propagates through conda-forge.

@ocefpaf (or another maintainer), could you create a dummy branch (e.g. `builds_with_hdf5_1.10.2`) that this could get merged into?  I'm not a maintainer here so I can't do that myself.

**Comment by mingwandroid** [comment]
Do you want to make a matrix build here? That's what we do: https://github.com/AnacondaRecipes/aggregate/blob/master/conda_build_config.yaml#L119-L121

**Comment by xylar** [comment]
> Do you want to make a matrix build here?
@mingwandroid, I'm definitely willing to give this a try.  @ocefpaf, do you think that would be a better approach?

**Comment by xylar** [comment]
The potential problem is that conda smithy appears to remove 1.10.2 on the next rerender.  So my guess is that conda smithy isn't intended to support matrix builds?

**Comment by mingwandroid** [comment]
Ah, well I have little idea about that side of things. @jakirkham, @ocefpaf, @mariusvniekerk may be able to help.

**Comment by ocefpaf** [comment]
@xylar we don't really need a build matrix for a 1-time build. Let's merge this as-is (I'm guessing you don't need Windows). I'll revert it once the package are in the channel.

**Comment by xylar** [comment]
Thanks @ocefpaf!  This got merged to master, rather than a dummy branch, so we'll want to revert the changes either now or in a future update.

**Comment by ocefpaf** [comment]
> Thanks @ocefpaf! This got merged to master, rather than a dummy branch, so we'll want to revert the changes either now or in a future update.

Don't worry. I'm already "reverting this" in #58

**Pull request merged**
