### PR TITLE
Add S3 support

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This is a straight-up port of @djhoese's PR to add S3 support, rebased onto the latest `main`.

### CODE REVIEW

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by djhoese** [comment]
I'll close #160 in favor of this. Note that this was based on work by others including @ocefpaf in #125 so if something is wrong with these flags I'm not sure I'm up to date on how it should work/change.

**Comment by zklaus** [comment]
I had to deactivate the tests for Zarr to make this work, but note that this seems to be mostly due to permissions. I will try to give an overview here of the failing tests and the reasons for the failures, taken from [the last attempted run](https://github.com/conda-forge/libnetcdf-feedstock/runs/14824708835) before switching off the tests.

## List of failed tests
- 224 - nczarr_test_run_ut_mapapi (Failed)
- 227 - nczarr_test_run_fillonlyz (Failed)
- 228 - nczarr_test_run_ncgen4 (Failed)
- 229 - nczarr_test_run_chunkcases (Failed)
- 230 - nczarr_test_run_purezarr (Failed)
- 233 - nczarr_test_run_nczarr_fill (Failed)
- 234 - nczarr_test_run_jsonconvention (Failed)
- 235 - nczarr_test_run_strings (Failed)
- 236 - nczarr_test_run_scalar (Failed)
- 237 - nczarr_test_run_nulls (Failed)
- 241 - nczarr_test_run_filter (Failed)
- 242 - nczarr_test_run_unknown (Failed)
- 243 - nczarr_test_run_specific_filters (Failed)

## 224 - nczarr_test_run_ut_mapapi (Failed)
This has a bunch of tests that mostly pass, but fails on attempted creation of a file in the unidata bucket, see https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=740636&view=logs&j=a05709b0-6e1e-5c64-5539-5c40db2d601d&t=6ff35a76-4d65-58c6-d0bb-61c2b88d027d&l=9203

## 227 - nczarr_test_run_fillonlyz (Failed)
Also fails on creation of a temporary file in the bucket, see https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=740636&view=logs&j=a05709b0-6e1e-5c64-5539-5c40db2d601d&t=6ff35a76-4d65-58c6-d0bb-61c2b88d027d&l=9421

## 228 - nczarr_test_run_ncgen4 (Failed)
Also fails on creation of a temporary file in the bucket, see https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=740636&view=logs&j=a05709b0-6e1e-5c64-5539-5c40db2d601d&t=6ff35a76-4d65-58c6-d0bb-61c2b88d027d&l=9476

## 229 - nczarr_test_run_chunkcases (Failed)
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=740636&view=logs&j=a05709b0-6e1e-5c64-5539-5c40db2d601d&t=6ff35a76-4d65-58c6-d0bb-61c2b88d027d&l=9577

## 230 - nczarr_test_run_purezarr (Failed)
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=740636&view=logs&j=a05709b0-6e1e-5c64-5539-5c40db2d601d&t=6ff35a76-4d65-58c6-d0bb-61c2b88d027d&l=9680

## 233 - nczarr_test_run_nczarr_fill (Failed)
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=740636&view=logs&j=a05709b0-6e1e-5c64-5539-5c40db2d601d&t=6ff35a76-4d65-58c6-d0bb-61c2b88d027d&l=9802

## 234 - nczarr_test_run_jsonconvention (Failed)
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=740636&view=logs&j=a05709b0-6e1e-5c64-5539-5c40db2d601d&t=6ff35a76-4d65-58c6-d0bb-61c2b88d027d&l=9905

## 235 - nczarr_test_run_strings (Failed)
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=740636&view=logs&j=a05709b0-6e1e-5c64-5539-5c40db2d601d&t=6ff35a76-4d65-58c6-d0bb-61c2b88d027d&l=9956

## 236 - nczarr_test_run_scalar (Failed)
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=740636&view=logs&j=a05709b0-6e1e-5c64-5539-5c40db2d601d&t=6ff35a76-4d65-58c6-d0bb-61c2b88d027d&l=10022

## 237 - nczarr_test_run_nulls (Failed)
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=740636&view=logs&j=a05709b0-6e1e-5c64-5539-5c40db2d601d&t=6ff35a76-4d65-58c6-d0bb-61c2b88d027d&l=10088

## 241 - nczarr_test_run_filter (Failed)
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=740636&view=logs&j=a05709b0-6e1e-5c64-5539-5c40db2d601d&t=6ff35a76-4d65-58c6-d0bb-61c2b88d027d&l=10500

## 242 - nczarr_test_run_unknown (Failed)
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=740636&view=logs&j=a05709b0-6e1e-5c64-5539-5c40db2d601d&t=6ff35a76-4d65-58c6-d0bb-61c2b88d027d&l=10653

## 243 - nczarr_test_run_specific_filters (Failed)
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=740636&view=logs&j=a05709b0-6e1e-5c64-5539-5c40db2d601d&t=6ff35a76-4d65-58c6-d0bb-61c2b88d027d&l=10699

**Comment by zklaus** [comment]
I think this is ready as is; we might also have a discussion about how to make the tests work.

**Review by ocefpaf — APPROVED** [review]

**Comment by dopplershift** [comment]
@DennisHeimbigner @WardF Can you all shed any light on those tests? Is there a correct incantation that non-Unidata folk can use to only run zarr tests for public data?

**Comment by DennisHeimbigner** [comment]
First, what actual netcdf-c version are you using? 4.9.2, I assume.

**Comment by dopplershift** [comment]
Yes, this PR is adding S3 support to the conda-forge builds for netcdf-c 4.9.2.

**Comment by DennisHeimbigner** [comment]
4.9.2 does not support S3 testing yet unless you have access to the Unidata S3 private bucket.

**Comment by zklaus** [comment]
@DennisHeimbigner, thanks, that's right. Do you object to the proposed course of action of merging the support here without re-activating the tests?

**Comment by DennisHeimbigner** [comment]
No objection on my part -- it your code. I will note that there are significant
changes in the handling of S3 testing in the next netcdf-c release, so you
may have to do this all over again.

**Comment by valeriupredoi** [comment]
hi @dopplershift just wanted to drop by thank @zklaus for this and also say we're eagerly awaiting this to be plopped in too :smiley: :eagle:

**Review by dopplershift — APPROVED** [review]

**Comment by zklaus** [comment]
Cheers and thanks everyone! :tada:

**Comment by valeriupredoi** [comment]
awesome, very many thanks @zklaus and @dopplershift :beer: x2

**Pull request merged**
