### PR TITLE
V4.9.0

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #139

### CODE REVIEW

**Comment by ocefpaf** [comment]
Linux is failing with:

```
/home/conda/feedstock_root/build_artifacts/libnetcdf_1655124967558/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../liblib/libnetcdf.a(ncjson.c.o): in function `NCJreclaim':
ncjson.c:(.text.NCJreclaim+0x0): multiple definition of `NCJreclaim'; CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o:NCZhdf5filters.c:(.text.NCJreclaim+0x0): first defined here
/home/conda/feedstock_root/build_artifacts/libnetcdf_1655124967558/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../liblib/libnetcdf.a(ncjson.c.o): in function `NCJnew':
ncjson.c:(.text.NCJnew+0x0): multiple definition of `NCJnew'; CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o:NCZhdf5filters.c:(.text.NCJnew+0x0): first defined here
/home/conda/feedstock_root/build_artifacts/libnetcdf_1655124967558/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../liblib/libnetcdf.a(ncjson.c.o): in function `NCJnewstringn':
ncjson.c:(.text.NCJnewstringn+0x0): multiple definition of `NCJnewstringn'; CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o:NCZhdf5filters.c:(.text.NCJnewstringn+0x0): first defined here
/home/conda/feedstock_root/build_artifacts/libnetcdf_1655124967558/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../liblib/libnetcdf.a(ncjson.c.o): in function `NCJnewstring':
ncjson.c:(.text.NCJnewstring+0x0): multiple definition of `NCJnewstring'; CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o:NCZhdf5filters.c:(.text.NCJnewstring+0x0): first defined here
/home/conda/feedstock_root/build_artifacts/libnetcdf_1655124967558/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../liblib/libnetcdf.a(ncjson.c.o): in function `NCJparse':
ncjson.c:(.text.NCJparse+0x0): multiple definition of `NCJparse'; CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o:NCZhdf5filters.c:(.text.NCJparse+0x0): first defined here
/home/conda/feedstock_root/build_artifacts/libnetcdf_1655124967558/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../liblib/libnetcdf.a(ncjson.c.o): in function `NCJdictget':
ncjson.c:(.text.NCJdictget+0x0): multiple definition of `NCJdictget'; CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o:NCZhdf5filters.c:(.text.NCJdictget+0x0): first defined here
/home/conda/feedstock_root/build_artifacts/libnetcdf_1655124967558/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: ../liblib/libnetcdf.a(ncjson.c.o): in function `NCJcvt':
ncjson.c:(.text.NCJcvt+0x0): multiple definition of `NCJcvt'; CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o:NCZhdf5filters.c:(.text.NCJcvt+0x0): first defined here
[ 32%] Building C object plugins/CMakeFiles/nczstdfilters.dir/NCZstdfilters.c.o
collect2: error: ld returned 1 exit status
make[2]: *** [plugins/CMakeFiles/nczhdf5filters.dir/build.make:118: plugins/lib__nczhdf5filters.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:2820: plugins/CMakeFiles/nczhdf5filters.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 32%] Linking CXX shared module lib__nczstdfilters.so
[ 32%] Built target nczstdfilters
make: *** [Makefile:166: all] Error 2
```

**Comment by dopplershift** [comment]
cc @WardF @DennisHeimbigner

**Comment by ocefpaf** [comment]
> I'll take a look to see how to duplicate and then fix this, and will round out our CI as needed; this isn't occurring on our end as-is. Thanks.

BTW, what version of zstd are you using in your CIs?

**Comment by DennisHeimbigner** [comment]
The json code occurs twice in our code base: once for use by plugins exclusively
and once for all the rest of the code. I suspect you are accidentally including both versions.
Note that the plugin version is constructed in the makefile from the other version.
If my speculation is correct, I will need to rethink how I build the json code.

**Comment by WardF** [comment]
> > I'll take a look to see how to duplicate and then fix this, and will round out our CI as needed; this isn't occurring on our end as-is. Thanks.
> 
> BTW, what version of zstd are you using in your CIs?

The version being installed by the underlying package manager, so let me see if I can extract that information.

**Comment by kmuehlbauer** [comment]
@WardF @DennisHeimbigner Did you had any time to look into this?

**Comment by kmuehlbauer** [comment]
@ocefpaf I've added a patch for this to the PR branch. Let's see if this works.

**Comment by kmuehlbauer** [comment]
Hmm, the created patch fails to apply...

**Comment by kmuehlbauer** [comment]
Maybe it wasn't worth the try. Hopefully 4.9.1 is out anytime soon.

**Comment by ocefpaf** [comment]
> Maybe it wasn't worth the try. Hopefully 4.9.1 is out anytime soon.

Definitely worth it! Thanks for the patch. Now are are hitting some failing tests:

```
ncdump_tst_nccopy4
nczarr_test_run_unknown
nczarr_test_run_specific_filters
```

**Comment by WardF** [comment]
Tagging for my own breadcrumb purposes, @WardF

**Comment by rsignell-usgs** [comment]
@dopplershift @WardF @DennisHeimbigner this is still broken??

**Comment by dopplershift** [comment]
Personally, I was waiting for 4.9.1 to try to fix the build issues, since there have been several identified and fixed since 4.9.0.

**Comment by DennisHeimbigner** [comment]
This should have been fixed with PR https://github.com/Unidata/netcdf-c/pull/2448
which apparently has been merged to master.
Are you in a position to verify the fix?

**Comment by dopplershift** [comment]
I'm putting together a patch right now based on that PR.

**Comment by dopplershift** [comment]
@DennisHeimbigner The actual build succeeds, but tests fail:
```
The following tests FAILED:
	 90 - nc_test_test_byterange (Failed)
	227 - nczarr_test_run_unknown (Failed)
	228 - nczarr_test_run_specific_filters (Failed)
```

**Comment by DennisHeimbigner** [comment]
Can you extract the test-suite.log file?

**Comment by dopplershift** [comment]
Clicking on "details" on the failed checks here will allow you to go to Azure and examine the build logs.

**Comment by hmaarrfk** [comment]
>  I forgot this is conda; is there anyway to get the test run output? 

I am running this locally now. What output are you looking for in particular?

**Comment by hmaarrfk** [comment]
Looking at the logs, I find:
```
2022-08-26T18:49:54.5767119Z 
2022-08-26T18:49:54.5767993Z 227: Test command: /usr/bin/bash "-c" "export srcdir=$SRC_DIR/nczarr_test;export TOPSRCDIR=$SRC_DIR;$SRC_DIR/nczarr_test/run_unknown.sh run_unknown.sh "
2022-08-26T18:49:54.5768770Z 227: Working Directory: $SRC_DIR/nczarr_test
2022-08-26T18:49:54.5769169Z 227: Test timeout computed to be: 1500
2022-08-26T18:49:54.5795853Z 227: /usr/bin/bash: $SRC_DIR/nczarr_test/run_unknown.sh: No such file or directory
2022-08-26T18:49:54.5809608Z 224/229 Test #227: nczarr_test_run_unknown ...............***Failed    0.00 sec
2022-08-26T18:49:54.5810289Z /usr/bin/bash: $SRC_DIR/nczarr_test/run_unknown.sh: No such file or directory
2022-08-26T18:49:54.5810602Z 
2022-08-26T18:49:54.5811024Z test 228
2022-08-26T18:49:54.5811423Z         Start 228: nczarr_test_run_specific_filters
2022-08-26T18:49:54.5811673Z 
2022-08-26T18:49:54.5812603Z 228: Test command: /usr/bin/bash "-c" "export srcdir=$SRC_DIR/nczarr_test;export TOPSRCDIR=$SRC_DIR;$SRC_DIR/nczarr_test/run_specific_filters.sh run_specific_filters.sh "
2022-08-26T18:49:54.5813223Z 228: Working Directory: $SRC_DIR/nczarr_test
2022-08-26T18:49:54.5813625Z 228: Test timeout computed to be: 1500
2022-08-26T18:49:54.5839292Z 228: /usr/bin/bash: $SRC_DIR/nczarr_test/run_specific_filters.sh: No such file or directory
2022-08-26T18:49:54.5853460Z 225/229 Test #228: nczarr_test_run_specific_filters ......***Failed    0.00 sec
2022-08-26T18:49:54.5854182Z /usr/bin/bash: $SRC_DIR/nczarr_test/run_specific_filters.sh: No such file or directory
2022-08-26T18:49:54.5854498Z 
```

**Comment by hmaarrfk** [comment]
These are visible from the current azure builds.

**Comment by DennisHeimbigner** [comment]
I am looking for the output from these three tests:
nc_test/test_byterange
nczarr_test/run_unknown (Failed)
nczarr_test/run_specific_filters (Failed)

**Comment by hmaarrfk** [comment]
Do they generate an output file? I'm really not sure how to get textual output any different than what can be seen on azure.

**Comment by hmaarrfk** [comment]
sorry for the silly questions

**Comment by xylar** [comment]
@hmaarrfk and @DennisHeimbigner, are we stuck here?  No suggestions for how to get more verbose output?

@ocefpaf and @hmaarrfk, I'm also wondering if it makes sense to include #135 in this PR?  It seems like a new release would be the appropriate point to split the package into dynamic and separate static.

**Comment by hmaarrfk** [comment]
Lets discuss #135 there.

**Comment by dopplershift** [comment]
@DennisHeimbigner I went and copied the azure logs and rans some `grep`s. Here's your output:

* nc_test/test_byterange
```
2022-08-26T18:49:30.0572703Z         Start  90: nc_test_test_byterange
2022-08-26T18:49:30.0573939Z 90: Test command: /usr/bin/bash "-c" "export srcdir=$SRC_DIR/nc_test;export TOPSRCDIR=$SRC_DIR;$SRC_DIR/nc_test/test_byterange.sh test_byterange.sh "
2022-08-26T18:49:30.0574539Z 90: Working Directory: $SRC_DIR/nc_test
2022-08-26T18:49:30.0574972Z 90: Test timeout computed to be: 1500
2022-08-26T18:49:30.0686415Z 90: 
2022-08-26T18:49:30.0700495Z 90: *** Testing reading NetCDF-3 file with http
2022-08-26T18:49:30.0701163Z 90: ***Test remote classic file
2022-08-26T18:49:30.4098727Z 90: $SRC_DIR/ncdump/ncdump: https://thredds-test.unidata.ucar.edu/thredds/fileServer/pointData/cf_dsg/example/point.nc#mode=bytes&aws.profile=none: NetCDF: Malformed URL
2022-08-26T18:49:30.4121256Z 90: test_http: -k flag mismatch: expected=classic have=
2022-08-26T18:49:30.4134086Z  91/229 Test  #90: nc_test_test_byterange ................***Failed    0.36 sec
```

* nczarr_test/run_unknown
```
2022-08-26T18:49:54.5766872Z         Start 227: nczarr_test_run_unknown
2022-08-26T18:49:54.5767993Z 227: Test command: /usr/bin/bash "-c" "export srcdir=$SRC_DIR/nczarr_test;export TOPSRCDIR=$SRC_DIR;$SRC_DIR/nczarr_test/run_unknown.sh run_unknown.sh "
2022-08-26T18:49:54.5768770Z 227: Working Directory: $SRC_DIR/nczarr_test
2022-08-26T18:49:54.5769169Z 227: Test timeout computed to be: 1500
2022-08-26T18:49:54.5795853Z 227: /usr/bin/bash: $SRC_DIR/nczarr_test/run_unknown.sh: No such file or directory
2022-08-26T18:49:54.5809608Z 224/229 Test #227: nczarr_test_run_unknown ...............***Failed    0.00 sec
```

* nczarr_test/run_specific_filters

```
2022-08-26T18:49:54.5811423Z         Start 228: nczarr_test_run_specific_filters
2022-08-26T18:49:54.5812603Z 228: Test command: /usr/bin/bash "-c" "export srcdir=$SRC_DIR/nczarr_test;export TOPSRCDIR=$SRC_DIR;$SRC_DIR/nczarr_test/run_specific_filters.sh run_specific_filters.sh "
2022-08-26T18:49:54.5813223Z 228: Working Directory: $SRC_DIR/nczarr_test
2022-08-26T18:49:54.5813625Z 228: Test timeout computed to be: 1500
2022-08-26T18:49:54.5839292Z 228: /usr/bin/bash: $SRC_DIR/nczarr_test/run_specific_filters.sh: No such file or directory
2022-08-26T18:49:54.5853460Z 225/229 Test #228: nczarr_test_run_specific_filters ......***Failed    0.00 sec
```

**Comment by WardF** [comment]
@dopplershift is it possible to assign this to me, for easy reference if nothing else? Those missing test scripts are... interesting, and suggest an environmental issue, maybe a knock-on effect from a test script somewhere that netcdf uses to configure the test environment?  I'll take a look so that @DennisHeimbigner doesn't have to shoulder it all himself.

**Comment by DennisHeimbigner** [comment]
The test_byterange failure is because it used a thredds-test URL.
The thredds-test server is permanently down. There is a fix in the
current main.

**Comment by DennisHeimbigner** [comment]
WRT nczarr_test/run_unknown
somehow the file nczarr_test/run_unknown.sh apparently got deleted.
Not sure how this happened.

**Comment by DennisHeimbigner** [comment]
WRT  nczarr_test/run_specific_filters
Same problem: this is a built file but it is either not being built
or is being deleted after creation.

**Comment by DennisHeimbigner** [comment]
See if this PR helps https://github.com/Unidata/netcdf-c/pull/2508

**Comment by xylar** [comment]
How would folks feel about dropping the static library as well in this release?  I don't have time to help with that now but it does seem like it would be cleaner to do that along with a new release, rather than in a separate build.

**Comment by dopplershift** [comment]
@DennisHeimbigner @WardF Still failing with the `Makefile.am` patch.

**Comment by DennisHeimbigner** [comment]
Three tests are failing:
* 90 - nc_test_test_byterange (Failed) -- this is failing because it is still referencing thredds-test server. This should have been fixed by PR [2491](https://github.com/Unidata/netcdf-c/pull/2491) which was merged into the main branch.
* 229 - nczarr_test_run_unknown (Failed)
    and
    230 - nczarr_test_run_specific_filters (Failed) -- these are still not being built, even though you are using PR [2508](https://github.com/Unidata/netcdf-c/pull/2508)

I am at a loss to explain why these PRs are not working.

**Comment by dopplershift** [comment]
@DennisHeimbigner I'm not an automake expert. Are changes to the `Makefile.am` used by default when using our GitHub tarballs, or do I need to trigger some regeneration step?

**Comment by WardF** [comment]
Looking at this was on my post-lunch list, but to answer your question @dopplershift, changes need to be regenerated using `autoreconf -if`.

**Comment by WardF** [comment]
@dopplershift CMake is all invoked on the spot, and doesn't have an equivalent.  If the changes were made to the appropriate `CMakeLists.txt` files, then they should be picked up when `cmake` is invoked.  Let me go take a look.

**Comment by DennisHeimbigner** [comment]
Those generated test files are not present in the tarballs.
It should be the case -- both cmake and automake -- that the those test
files are generated at build time. So assuming you use the cmake command
and/or /configure + make commands, those test cases should have been
generated. If absolutely necessary, I can include those generated files
in the repository (hence also the tarball).

**Comment by WardF** [comment]
So diving in, and thinking half out-loud to myself, I'm seeing the following in some of the failures: 

````
197: Test command: /usr/bin/bash "-c" "export srcdir=$SRC_DIR/ncdap_test;export TOPSRCDIR=$SRC_DIR;$SRC_DIR/ncdap_test/tst_ncdap3.sh tst_ncdap3.sh "
````
I would *expect* that `$SRC_DIR` would be expanded here to the actual value of the environmental variable; perhaps it is, and is just not being verbosely reported in the log? But if it's not, that is absolutely going to be one of the issues at play XD.

**Comment by hmaarrfk** [comment]
i think..... that conda's bulid systems replace standard variables with their shorthand. They get very long...

**Comment by xylar** [comment]
I know you all are focused on getting this release to build at all, but please consider providing your thoughts on my earlier question:

> How would folks feel about dropping the static library as well in this release? I don't have time to help with that now but it does seem like it would be cleaner to do that along with a new release, rather than in a separate build.

For context, @hmaarrfk and I had a conversation about splitting the package into dynamic and static here: 
https://github.com/conda-forge/libnetcdf-feedstock/pull/135#issuecomment-1249302064
@hmaarrfk feels that we should just drop the static library and split the package only if we then find out that downstream package require it.  Otherwise, it's a big headache.

But it seems like dropping the static library should happen with a new package release, and better if it's a minor, rather than a micro, version change like here.

**Comment by WardF** [comment]
> I know you all are focused on getting this release to build at all, but please consider providing your thoughts on my earlier question:
> 
> 
> 
> > How would folks feel about dropping the static library as well in this release? I don't have time to help with that now but it does seem like it would be cleaner to do that along with a new release, rather than in a separate build.
> 
> 
> 
> For context, @hmaarrfk and I had a conversation about splitting the package into dynamic and static here: 
> 
> https://github.com/conda-forge/libnetcdf-feedstock/pull/135#issuecomment-1249302064
> 
> @hmaarrfk feels that we should just drop the static library and split the package only if we then find out that downstream package require it.  Otherwise, it's a big headache.
> 
> 
> 
> But it seems like dropping the static library should happen with a new package release, and better if it's a minor, rather than a micro, version change like here.

Insofar as my thoughts go, I tend to prefer shared libraries in general. But I operate pretty far outside the Python/Conda ecosystem, so I have very little intuition for what that change would mean for the users in those spaces.

**Comment by hmaarrfk** [comment]
FWIW:
It seems that the pypi wheels use the shared libraries. That used to be my concern a few years ago.
image

**Comment by ocefpaf** [comment]
@xylar and @hmaarrfk I'm OK dropping the static library build. I don't think we have anyone using those at the moment.

**Comment by WardF** [comment]
I believe I may have a fix for the test failures observed above; I'm testing the `mpi`-based tests now, but for the `nompi` option, at least, the fix appears to be working.  I'll provide more details once I can confirm the fix works more broadly.

**Comment by WardF** [comment]
It looks like one of the `nccopy` tests may have a race condition, but the observed failures at the root of this issue *appear* to have been resolved; once the race condition is confirmed & addressed, I'll put up the fix (which also incorporates this PR).

**Comment by WardF** [comment]
I've just noticed that the test failure in `win win_64_` is completely different from the other tests observed; my fix isn't addressing that, perhaps somebody more familiar with the feedstock workflow can take a look at that? I will as well, time permitting, but am currently focusing on the libnetcdf-specific issue.

**Comment by WardF** [comment]
It looks like this is passing and ready for somebody else to review and merge.  Thanks all!

**Comment by WardF** [comment]
@ocefpaf I wanted to have one out by the end of the month, and that could still happen; if it's not out this week, I'm going to try to have it out next week.  This was the largest blocking issue to resolve, but I still have some documentation to add and/or revamp, among all the other sundy day-to-day items we all deal with XD.  I don't have any particular insight into the workflow and/or implications of skipping this version in libnetcdf-feedstock, however, so I'll leave that for a broader group discussion :)

**Comment by xylar** [comment]
@WardF and @ocefpaf, can I push a commit to remove static library builds?  It seems like everything else i in place.

**Comment by xylar** [comment]
Sorry, just getting caught up on the conversation.  It sounds like it doesn't make sense to push anymore changes to the branch until we know if we're merging this or waiting for 4.9.1.

**Comment by WardF** [comment]
Having thought about it, I believe this should be merged; I'll also ensure the patches contained in this (and, moving forward, other) PR's find their way back upstream into the `netcdf-c` repo.

**Comment by dopplershift** [comment]
With the exception of the ncjson patch (taken from upstream), all the patches added here tweak CMake/a few tests (and associated build files), so I'm comfortable that what we have here is fine and would be comfortable merging.

@xylar do you want to make the changes to eliminate the static build?

**Comment by xylar** [comment]
Thanks, @hmaarrfk!  Those are almost exactly the commits I had staged.  Except that I didn't think to check that the static library is *not* there, which is excellent!

**Comment by hmaarrfk** [comment]
I think i got it.

**Review by xylar — APPROVED** [review]
Assuming CI passes, I'm very happy to see this merged.

**Comment by dopplershift** [comment]
With all that said, we probably want to wait for the (soon-to-be-released) 4.9.1 to think about migrating downstream compiled packages.

**Comment by xylar** [comment]
@dopplershift, I think that probably makes sense.  Have this version available but not migrate to it?

**Comment by dopplershift** [comment]
@xylar Yeah. We can always decide to migrate if for some reason 4.9.1 becomes delayed, but that shouldn't be the case. No need to do two migrations in rapid succession, but having it available can also allow for some more testing by interested users.

**Comment by xylar** [comment]
Who dares hit the green button?

**Pull request merged**
