### PR TITLE
Update recipe

### PR DESCRIPTION
**Pull request by ocefpaf**
This is probably my last update to `v4.4`. I'll drop Python 2 support on Windows in all places that depends on `libnetcdf` soon.

### CODE REVIEW

**Comment by ocefpaf** [comment]
The Windows failure here is a major block for all things that depend on `gdal` but are now broken due to the `hdf5 1.10.2` pin update.

**Comment by ocefpaf** [comment]
@gillins do you have any clue on how to fix this?

```
-- Found JPEG libraries: C:/bld/libnetcdf_1530361293972/_b_env/Library/lib/jpeg.lib
CMake Error at CMakeLists.txt:612 (FIND_PACKAGE):
  Could not find a package configuration file provided by "HDF5" with any of
  the following names:
    HDF5Config.cmake
    hdf5-config.cmake
  Add the installation prefix of "HDF5" to CMAKE_PREFIX_PATH or set
  "HDF5_DIR" to a directory containing one of the above files.  If "HDF5"
  provides a separate development package or SDK, be sure it has been
  installed.
-- Configuring incomplete, errors occurred!
See also "C:/bld/libnetcdf_1530361293972/work/netcdf-c-4.6.1/build/CMakeFiles/CMakeOutput.log".
```

**Comment by gillins** [comment]
Maybe try adding `-D HDF5_DIR=%LIBRARY_PREFIX%\cmake\hdf5 ^` to `bld.bat`? I'll try and have a proper look later.

**Comment by ocefpaf** [comment]
> Maybe try adding `-D HDF5_DIR=%LIBRARY_PREFIX%\cmake\hdf5 ^` to `bld.bat`? I'll try and have a proper look later.

Worth a try :smile:

**Pull request merged**
