### PR TITLE
Bump build version

### PR DESCRIPTION
**Pull request by jschueller**
@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@jschueller In Travis we get the same error in the other [PR](https://github.com/conda-forge/libnetcdf-feedstock/pull/61). This was not happening before the updated hdf5 pinning (1.10.3 -> 1.10.4).

**Comment by jschueller** [comment]
The traceback leads to conda-build:
```
Traceback (most recent call last):
  File "/Users/travis/miniconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/travis/miniconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 197, in rewriter
    line = r.readline()
  File "/Users/travis/miniconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 201: invalid start byte
```

**Comment by ocefpaf** [comment]
@jschueller sorry for merging #58 first. I missed this one. Do you still need this version with latest hdf5?

**Comment by jschueller** [comment]
it's ok, did you report the failure to conda-build ?

**Comment by ocefpaf** [comment]
> it's ok, did you report the failure to conda-build ?

I did not. I haven't look into that...

**Pull request closed without merging**
