### PR TITLE
Depend on libxml2

### PR DESCRIPTION
**Pull request by jschueller**
see #155

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by xylar** [comment]
@jschueller, thanks very much for working on this!  Please let us know when it's ready to review/merge.

**Comment by jschueller** [comment]
it's ready

**Comment by xylar** [comment]
Great, thanks again!

**Pull request merged**
