### PR TITLE
Fix cmake export targets

### LINKED ISSUE #173: cmake imported target might be broken
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I have the impression that the latest libnetcdf package on conda-forge causes problems when using libnetcdf as a cmake imported target. The cmake imported target somehow causes the fimex build to expect libz.so in the fimex build directory, and libz.so is obviously not there:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=676229&view=logs&jobId=4f922444-fdfe-5dcf-b824-02f86439ef14&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=b2a8456a-fb11-5506-ca32-5ccd32538dc0

(See line 499 in the build output.) This problem has not been present in previous libnetcdf versions, and is not present when using libnetcdf via pkg-config instead of as a cmake imported target.

### Installed packages

```shell
conda build
```

### Environment info

```shell
conda version : 23.1.0
    conda-build version : 3.24.0
         python version : 3.8.16.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.27=0
                          __linux=4.15.0=0
                          __unix=0=0
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.8.16 Linux/4.15.0-206-generic ubuntu/18.04.6 glibc/2.27
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #173

### CODE REVIEW

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by alexander-buerger-met-no** [comment]
Yes, this looks good to me. But I think that there is a small typo in the explanatory comment in meta.yaml: "principal" should probably be "principle".

**Comment by zklaus** [comment]
@conda-forge-admin, please restart ci

**Comment by zklaus** [comment]
@conda-forge-admin, please restart ci

**Comment by zklaus** [comment]
@conda-forge-admin, please restart ci

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
Hm, I think this is ready, but somehow the CI isn't springing into action. @conda-forge/libnetcdf, does anyone have an idea why?

**Comment by xylar** [comment]
Seeing the same here:
https://github.com/conda-forge/esmf-feedstock/pull/108

Something must be going wrong more broadly.

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
After a brief hiccup with the CI, this is now ready for review, @conda-forge/libnetcdf.

**Review by xylar — APPROVED** [review]

**Comment by xylar** [comment]
Thanks for adding that lengthy and helpful comment, @zklaus.

**Pull request merged**
