### PR TITLE
Hdf4

### PR DESCRIPTION
**Pull request by ocefpaf**
Not sure if we will need to specify `hdf4` paths here...

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@ocefpaf Thanks for taking the chance. The appveyor failure seems due to the Backslash instead of ^.

**Comment by ocefpaf** [comment]
> The appveyor failure seems due to the Backslash instead of ^.

Indeed. I did not paid the proper attention this test deserves. Fixing that...

**Comment by kmuehlbauer** [comment]
@ocefpaf Great! It's picked up now correctly. So it was just that single line. Thanks again!

**Comment by ocefpaf** [comment]
> @ocefpaf Great! It's picked up now correctly. So it was just that single line. Thanks again!

Awesome! Let's hope that is enough to fix the issue you are seeing.

**Comment by ocefpaf** [comment]
@kmuehlbauer do you want to be a maintainer here :grimacing:  ?

**Comment by kmuehlbauer** [comment]
As it is one foundation of my used conda stack, this might be a good idea. But the latest development concerning conda-forge was that fast, that I have lost track. Anyway, Let's do it!

**Comment by ocefpaf** [comment]
>  But the latest development concerning conda-forge was that fast, that I have lost track.

Don't worry. We all did :wink:

**Comment by kmuehlbauer** [comment]
@ocefpaf This seems ready to merge. I'll test and report back, when this gets uploaded to anaconda. 👍

**Comment by ocefpaf** [comment]
Thanks for the ping ;-)

**Comment by kmuehlbauer** [comment]
Works as espected 🎉 ! Huge thanks for the quick fix @ocefpaf.

**Pull request merged**
