### PR TITLE
Debug

### PR DESCRIPTION
**Pull request by ocefpaf**
Trying to debug #10

cc.: @jbosch-noaa this exposes the problem you are experiencing on Windows with the latest version of `libnetcdf`. I am investigating possible solutions.

xref: https://github.com/Unidata/netcdf-c/issues/365

### CODE REVIEW

**Comment by ocefpaf** [comment]
Only the `https` URLs are failing. @dopplershift do you have any idea where we should look?

**Comment by dopplershift** [comment]
I can't seem to reproduce this any more--our workshop notebooks run fine. The only problem I've had is that NCDC seems to have re-arranged the THREDDS server on NOMADS, so a dataset we used is gone. Sorry I'm not of more help...

**Comment by ocefpaf** [comment]
>  Sorry I'm not of more help...

No problem. I don't have time to investigate why the `https` endpotins are failing now but I will get back to this soon.

**Comment by dopplershift** [comment]
Correction--I missed that I had the version pinned. Here's a URL that fails for me with OPENDAP access:
http://thredds.ucar.edu/thredds/dodsC/grib/NCEP/GFS/Global_0p5deg/GFS_Global_0p5deg_20170215_1200.grib2

**Comment by ocefpaf** [comment]
Thanks for the feedback. I was under the impression that only `https` endpoints were failing but yours is not `https` :unamused:

**Comment by dopplershift** [comment]
And to be clear, that's on Python 3.4--I'll check 3.5.

**Comment by dopplershift** [comment]
I've reproduced with Unidata's pre-built binaries on 64-bit win 10, so I don't think this is conda-forge's problem.

**Comment by ocefpaf** [comment]
> I've reproduced with Unidata's pre-built binaries on 64-bit win 10, so I don't think this is conda-forge's problem.

Good to know. Are you opening an issue there for this or should I?

**Comment by dopplershift** [comment]
I've handed it off to the netCDF-C team--they'll open an issue there when they know more. At that point, I'll link here.

**Comment by ocefpaf** [comment]
Even though this is failing I am merging so we can have the new test ready when the new release comes out. See https://github.com/Unidata/netcdf-c/pull/366 for the fix.

**Pull request merged**
