### PR TITLE
Workaround broken cmake config file

### PR DESCRIPTION
**Pull request by jschueller**
try to work around https://github.com/Unidata/netcdf-c/issues/1444
we manually pass hdf5 variables to avoid the find_package path which results in target names being added to cmake target config files instead of actual library paths.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@jschueller @xylar Sorry for being late to the party. Not sure if this helps, but it seems the issue will be solved netcdf-c, see https://github.com/Unidata/netcdf-c/commit/023d3e92dfc7679dec8a9e16790aced74533a296.

Asking @WardF if this will fix the issue?

**Comment by jschueller** [comment]
yes, dont merge anything yet, i'll try to backport in another pr

**Comment by xylar** [comment]
@jschueller, it might be worth adding yourself as a maintainer.

**Comment by WardF** [comment]
> @jschueller @xylar Sorry for being late to the party. Not sure if this helps, but it seems the issue will be solved netcdf-c, see [Unidata/netcdf-c@023d3e9](https://github.com/Unidata/netcdf-c/commit/023d3e92dfc7679dec8a9e16790aced74533a296).
> 
> Asking @WardF if this will fix the issue?

That branch will fix it, but not as it currently stands.  HDF5 logic is tricky, and I need to port over some additional work from the netcdf-c/CMakeLists.txt file :).

**Comment by kmuehlbauer** [comment]
> > @jschueller @xylar Sorry for being late to the party. Not sure if this helps, but it seems the issue will be solved netcdf-c, see [Unidata/netcdf-c@023d3e9](https://github.com/Unidata/netcdf-c/commit/023d3e92dfc7679dec8a9e16790aced74533a296).
> > Asking @WardF if this will fix the issue?
> 
> That branch will fix it, but not as it currently stands. HDF5 logic is tricky, and I need to port over some additional work from the netcdf-c/CMakeLists.txt file :).

@WardF Thanks for the update, much appreciated!

**Comment by jschueller** [comment]
I propose to merge this PR untils the fix lands in a netcdf to let wardf time to investigate.

**Comment by xylar** [comment]
I'm going to give folks the rest of today to comment one way or the other and then I'll merge.

**Pull request merged**
