### PR TITLE
Bump rc

### PR DESCRIPTION
**Pull request by dopplershift**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Ok, let's see how 4.9.1 rc1 builds. My plan is to also see if some of those other patches can be removed, or if they need to be upstreamed.

### CODE REVIEW

**Comment by dopplershift** [comment]
So linux and Windows are failing with:
```
-- Configuring done
CMake Error at libsrc/CMakeLists.txt:37 (add_library):
  Cannot find source file:

    D:/bld/libnetcdf_1666379359313/work/build/libsrc/putget.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at nc_test/CMakeLists.txt:31 (ADD_EXECUTABLE):
  Cannot find source file:

    D:/bld/libnetcdf_1666379359313/work/build/nc_test/test_get.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at libsrc/CMakeLists.txt:37 (add_library):
  No SOURCES given to target: netcdf3


CMake Error at nc_test/CMakeLists.txt:31 (ADD_EXECUTABLE):
  No SOURCES given to target: nc_test
-- Cache values
```

@WardF?

**Comment by dopplershift** [comment]
Ok, with m4 added to the build tools (osx already had it installed) (@WardF I don't think you intended for m4 to be needed?), we now get to:
```
[ 19%] Building C object libnczarr/CMakeFiles/nczarr.dir/zutil.c.o
[ 19%] Building C object oc2/CMakeFiles/oc2.dir/xxdr.c.o
In file included from /home/conda/feedstock_root/build_artifacts/libnetcdf_1666381046563/_build_env/x86_64-conda-linux-gnu/sysroot/usr/include/string.h:637,
                 from /home/conda/feedstock_root/build_artifacts/libnetcdf_1666381046563/work/libnczarr/zincludes.h:22,
                 from /home/conda/feedstock_root/build_artifacts/libnetcdf_1666381046563/work/libnczarr/zutil.c:13:
/home/conda/feedstock_root/build_artifacts/libnetcdf_1666381046563/work/libnczarr/zutil.c: In function 'ncz_nctype2dtype':
/home/conda/feedstock_root/build_artifacts/libnetcdf_1666381046563/work/libnczarr/zutil.c:544:26: error: called object 'strlen' is not a function or function pointer
  544 |     if(dnamep) *dnamep = strdup(dname);
      |                          ^~~~~~
/home/conda/feedstock_root/build_artifacts/libnetcdf_1666381046563/work/libnczarr/zutil.c:533:68: note: declared here
  533 | ncz_nctype2dtype(nc_type nctype, int endianness, int purezarr, int strlen, char** dnamep)
      |                                                                ~~~~^~~~~~
make[2]: *** [libnczarr/CMakeFiles/nczarr.dir/build.make:356: libnczarr/CMakeFiles/nczarr.dir/zutil.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2608: libnczarr/CMakeFiles/nczarr.dir/all] Error 2
```

I wonder if that's related to the strdup patch I thought wasn't needed any more...I'll wait to see all the build results first.

**Comment by dopplershift** [comment]
Ok, well that accomplished nothing, so I'll pop that back off.

**Comment by WardF** [comment]
Leaving a breadcrumb for myself here to pick this back up if/when I get distracted by other tasks.

**Comment by WardF** [comment]
This will be a known issue in rc1 since we are about to release that, but I will iterate on it for rc2.

**Comment by dopplershift** [comment]
@WardF Just two test failures on the linux x86_64 nompi build, no more build failures:
```
2022-11-08T18:42:20.5330242Z         Start  31: ncdump_tst_bom
2022-11-08T18:42:20.5340121Z 31: Test command: /usr/bin/bash "-c" "export srcdir=$SRC_DIR/ncdump;export TOPSRCDIR=$SRC_DIR;$SRC_DIR/build-shared/ncdump/tst_bom.sh tst_bom.sh "
2022-11-08T18:42:20.5345025Z 31: Working Directory: $SRC_DIR/build-shared/ncdump
2022-11-08T18:42:20.5349045Z 31: Test timeout computed to be: 1500
2022-11-08T18:42:20.5483356Z 31: 
2022-11-08T18:42:20.5513641Z 31: *** Generate a cdl file with leading UTF-8 BOM.
2022-11-08T18:42:20.5539130Z 31: *** Verify .nc file
2022-11-08T18:42:20.5725427Z 31: 6a7,69
2022-11-08T18:42:20.5730326Z 31: > }
2022-11-08T18:42:20.5734514Z 31: > riables:
2022-11-08T18:42:20.5738438Z 31: > 	float var(dim) ;
2022-11-08T18:42:20.5742716Z 31: > 		var:units = "m/s" ;
2022-11-08T18:42:20.5746504Z 31: > 
2022-11-08T18:42:20.5750609Z 31: > // global attributes:
2022-11-08T18:42:20.5754458Z 31: > 		:title = "for testing groups" ;
2022-11-08T18:42:20.5758346Z 31: > data:
2022-11-08T18:42:20.5770376Z 31: > 
2022-11-08T18:42:20.5770829Z 31: >  var = 1, 2, 3, 4 ;
2022-11-08T18:42:20.5771107Z 31: > 
2022-11-08T18:42:20.5771347Z 31: > group: g1 {
2022-11-08T18:42:20.5771653Z 31: >   dimensions:
2022-11-08T18:42:20.5771941Z 31: >   	dim = 1 ;
2022-11-08T18:42:20.5772211Z 31: >   variables:
2022-11-08T18:42:20.5772505Z 31: >   	float var(dim) ;
2022-11-08T18:42:20.5772817Z 31: >   		var:units = "km/hour" ;
2022-11-08T18:42:20.5773111Z 31: > 
2022-11-08T18:42:20.5773381Z 31: >   // group attributes:
2022-11-08T18:42:20.5773701Z 31: >   		:title = "in first group" ;
2022-11-08T18:42:20.5773992Z 31: >   data:
2022-11-08T18:42:20.5774254Z 31: > 
2022-11-08T18:42:20.5774502Z 31: >    var = 1 ;
2022-11-08T18:42:20.5774790Z 31: >   } // group g1
2022-11-08T18:42:20.5775063Z 31: > 
2022-11-08T18:42:20.5775318Z 31: > group: g2 {
2022-11-08T18:42:20.5775615Z 31: >   dimensions:
2022-11-08T18:42:20.5775886Z 31: >   	dim = 2 ;
2022-11-08T18:42:20.5776164Z 31: >   variables:
2022-11-08T18:42:20.5776441Z 31: >   	float var(dim) ;
2022-11-08T18:42:20.5776754Z 31: >   		var:units = "cm/sec" ;
2022-11-08T18:42:20.5777037Z 31: > 
2022-11-08T18:42:20.5777310Z 31: >   // group attributes:
2022-11-08T18:42:20.5777618Z 31: >   		:title = "in second group" ;
2022-11-08T18:42:20.5777924Z 31: >   data:
2022-11-08T18:42:20.5778168Z 31: > 
2022-11-08T18:42:20.5778435Z 31: >    var = 1, 2 ;
2022-11-08T18:42:20.5781092Z 31: > 
2022-11-08T18:42:20.5781387Z 31: >   group: g3 {
2022-11-08T18:42:20.5781685Z 31: >     dimensions:
2022-11-08T18:42:20.5781960Z 31: >     	dim = 3 ;
2022-11-08T18:42:20.5782255Z 31: >     variables:
2022-11-08T18:42:20.5782534Z 31: >     	float var(dim) ;
2022-11-08T18:42:20.5782851Z 31: >     		var:units = "mm/msec" ;
2022-11-08T18:42:20.5783352Z 31: >     	float var2(/dim, /g2/dim, dim) ;
2022-11-08T18:42:20.5783654Z 31: > 
2022-11-08T18:42:20.5783932Z 31: >     // group attributes:
2022-11-08T18:42:20.5784259Z 31: >     		:title = "in third group" ;
2022-11-08T18:42:20.5784566Z 31: >     data:
2022-11-08T18:42:20.5784818Z 31: > 
2022-11-08T18:42:20.5785090Z 31: >      var = 1, 2, 3 ;
2022-11-08T18:42:20.5785360Z 31: > 
2022-11-08T18:42:20.5785619Z 31: >      var2 =
2022-11-08T18:42:20.5785880Z 31: >   1, 2, 3,
2022-11-08T18:42:20.5786155Z 31: >   4, 5, 6,
2022-11-08T18:42:20.5786418Z 31: >   7, 8, 9,
2022-11-08T18:42:20.5786697Z 31: >   10, 11, 12,
2022-11-08T18:42:20.5786970Z 31: >   13, 14, 15,
2022-11-08T18:42:20.5787254Z 31: >   16, 17, 18,
2022-11-08T18:42:20.5787525Z 31: >   19, 20, 21,
2022-11-08T18:42:20.5787809Z 31: >   22, 23, 24 ;
2022-11-08T18:42:20.5788096Z 31: >     } // group g3
2022-11-08T18:42:20.5788337Z 31: >   } // group g2
2022-11-08T18:42:20.5809284Z  40/233 Test  #31: ncdump_tst_bom ........................***Failed    0.05 sec
```

and

```
2022-11-08T18:42:20.4593481Z         Start  58: ncdump_tst_nccopy4
2022-11-08T18:42:20.4596281Z 58: Test command: /usr/bin/bash "-c" "export srcdir=$SRC_DIR/ncdump;export TOPSRCDIR=$SRC_DIR;$SRC_DIR/build-shared/ncdump/tst_nccopy4.sh tst_nccopy4.sh "
2022-11-08T18:42:20.4597071Z 58: Working Directory: $SRC_DIR/build-shared/ncdump
2022-11-08T18:42:20.4597481Z 58: Test timeout computed to be: 1500
2022-11-08T18:42:20.4597787Z 58: 
2022-11-08T18:42:20.4598363Z 58: *** Testing groups.
2022-11-08T18:42:20.4598713Z 58: *** creating nested group file tst_group_data.nc...ok.
2022-11-08T18:42:20.4599109Z 58: *** Tests successful!
2022-11-08T18:42:20.4599372Z 58: 
2022-11-08T18:42:20.4599663Z 58: *** Testing enums.
2022-11-08T18:42:20.4600007Z 58: *** creating enum test file tst_enum_data.nc...ok.
2022-11-08T18:42:20.4600362Z 58: *** Tests successful!
2022-11-08T18:42:20.4600629Z 58: 
2022-11-08T18:42:20.4600895Z 58: *** Testing compound types.
2022-11-08T18:42:20.4601252Z 58: *** creating compound test file tst_comp.nc...ok.
2022-11-08T18:42:20.4601589Z 58: *** Tests successful!
2022-11-08T18:42:20.4601867Z 58: 
2022-11-08T18:42:20.4602145Z 58: *** Testing compound types some more.
2022-11-08T18:42:20.4602542Z 58: *** creating another compound test file tst_comp2.nc...ok.
2022-11-08T18:42:20.4603388Z 58: *** Tests successful!
2022-11-08T18:42:20.4603698Z 58: 
2022-11-08T18:42:20.4604299Z 58: *** Testing netCDF-4 features of nccopy on ncdump/*.nc files
2022-11-08T18:42:20.4604747Z 58: *** Test nccopy tst_comp.nc copy_of_tst_comp.nc ...
2022-11-08T18:42:20.4605156Z 58: *** compare  with copy_of_tst_comp.cdl
2022-11-08T18:42:20.4605598Z 58: *** Test nccopy tst_comp2.nc copy_of_tst_comp2.nc ...
2022-11-08T18:42:20.4605975Z 58: *** compare  with copy_of_tst_comp2.cdl
2022-11-08T18:42:20.4606363Z 58: *** Test nccopy tst_enum_data.nc copy_of_tst_enum_data.nc ...
2022-11-08T18:42:20.4606737Z 58: *** compare  with copy_of_tst_enum_data.cdl
2022-11-08T18:42:20.4607109Z 58: *** Test nccopy tst_fillbug.nc copy_of_tst_fillbug.nc ...
2022-11-08T18:42:20.4607529Z 58: *** compare  with copy_of_tst_fillbug.cdl
2022-11-08T18:42:20.4607905Z 58: *** Test nccopy tst_group_data.nc copy_of_tst_group_data.nc ...
2022-11-08T18:42:20.4609974Z 58: *** compare  with copy_of_tst_group_data.cdl
2022-11-08T18:42:20.4610350Z 58: *** Test nccopy tst_nans.nc copy_of_tst_nans.nc ...
2022-11-08T18:42:20.4610709Z 58: *** compare  with copy_of_tst_nans.cdl
2022-11-08T18:42:20.4611631Z 58: *** Test nccopy tst_opaque_data.nc copy_of_tst_opaque_data.nc ...
2022-11-08T18:42:20.4617074Z 58: *** compare  with copy_of_tst_opaque_data.cdl
2022-11-08T18:42:20.4617478Z 58: *** Test nccopy tst_solar_1.nc copy_of_tst_solar_1.nc ...
2022-11-08T18:42:20.4631343Z 58: *** compare  with copy_of_tst_solar_1.cdl
2022-11-08T18:42:20.4631748Z 58: *** Test nccopy tst_solar_2.nc copy_of_tst_solar_2.nc ...
2022-11-08T18:42:20.4655657Z 58: *** compare  with copy_of_tst_solar_2.cdl
2022-11-08T18:42:20.4664150Z 58: *** Test nccopy tst_solar_cmp.nc copy_of_tst_solar_cmp.nc ...
2022-11-08T18:42:20.4690825Z 58: *** compare  with copy_of_tst_solar_cmp.cdl
2022-11-08T18:42:20.4691536Z 58: *** Test nccopy tst_special_atts.nc copy_of_tst_special_atts.nc ...
2022-11-08T18:42:20.4698348Z 58: *** compare  with copy_of_tst_special_atts.cdl
2022-11-08T18:42:20.4784035Z 58: *** Test nccopy tst_string_data.nc copy_of_tst_string_data.nc ...
2022-11-08T18:42:20.4792653Z 58: *** compare  with copy_of_tst_string_data.cdl
2022-11-08T18:42:20.4797373Z 58: *** Creating compressible test files tst_inflated.nc, tst_inflated4.nc...ok.
2022-11-08T18:42:20.4797769Z 58: *** Tests successful!
2022-11-08T18:42:20.4798300Z 58: *** Test nccopy -d1 can compress a classic format file ...
2022-11-08T18:42:20.4814143Z 58: *** Test nccopy -d1 can compress a netCDF-4 format file ...
2022-11-08T18:42:20.4821611Z 58: *** Test nccopy -d1 -s can compress a classic model netCDF-4 file even more ...
2022-11-08T18:42:20.4826009Z 58: *** Test nccopy -d1 -s can compress a netCDF-4 file even more ...
2022-11-08T18:42:20.4828367Z 58: *** Test nccopy -d0 turns off compression, shuffling of compressed, shuffled file ...
2022-11-08T18:42:20.4830613Z 58: *** Testing nccopy -d1 -s on ncdump/*.nc files
2022-11-08T18:42:20.4831143Z 58: *** Test nccopy -d1 -s tst_comp.nc copy_of_tst_comp.nc ...
2022-11-08T18:42:20.4835488Z 58: *** Test nccopy -d1 -s tst_comp2.nc copy_of_tst_comp2.nc ...
2022-11-08T18:42:20.4841004Z 58: *** Test nccopy -d1 -s tst_enum_data.nc copy_of_tst_enum_data.nc ...
2022-11-08T18:42:20.5083586Z 58: *** Test nccopy -d1 -s tst_fillbug.nc copy_of_tst_fillbug.nc ...
2022-11-08T18:42:20.5443041Z 58: *** Test nccopy -d1 -s tst_group_data.nc copy_of_tst_group_data.nc ...
2022-11-08T18:42:20.5898947Z 58: 1,3c1
2022-11-08T18:42:20.5904126Z 58: < netcdf copy_of_tst_group_data {
2022-11-08T18:42:20.5908702Z 58: < dimensions:
2022-11-08T18:42:20.5912966Z 58: < 	dim = 4 ;
2022-11-08T18:42:20.5917789Z 58: ---
2022-11-08T18:42:20.5940479Z 58: > netcdf tst_bom {
2022-11-08T18:42:20.5940951Z 58: 4a3,8
2022-11-08T18:42:20.5941235Z 58: > 	float f ;
2022-11-08T18:42:20.5941513Z 58: > data:
2022-11-08T18:42:20.5941767Z 58: > 
2022-11-08T18:42:20.5942037Z 58: >  f = 1 ;
2022-11-08T18:42:20.5942299Z 58: > }
2022-11-08T18:42:20.5942565Z 58: > riables:
2022-11-08T18:42:20.5948075Z  41/233 Test  #58: ncdump_tst_nccopy4 ....................***Failed    0.84 sec
```

which I'll note are running simultaneously.

**Comment by dopplershift** [comment]
Diagnosed and reported upstream as Unidata/netcdf-c#2551.

**Comment by dopplershift** [comment]
Ok, all but 1 of the build failures is failing conda-forge's tests because DAP4 isn't ending up enabled even though we pass `-DENABLE_DAP=ON`. Waiting to see if that's intentional at this point.

The other failure was hitting another test race condition that's been filed upstream as Unidata/netcdf-c#2562.

**Comment by dopplershift** [comment]
Ok, with an updated tag the only failures are due to test race conditions.

**Comment by WardF** [comment]
Fun. Thanks.  I'll take a look at the fenceposting in autotools and cmake, to hopefully avoid similar failures.

**Pull request merged**
