### PR TITLE
Add mpi build

### PR DESCRIPTION
**Pull request by ocefpaf**
xref.: https://github.com/conda-forge/netcdf4-feedstock/issues/43#issuecomment-491799367

Ping @annefou.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Failing with:

```
test 140
        Start 140: nc_test4_run_par_test

140: Test command: /bin/bash "-c" "export srcdir=$SRC_DIR/nc_test4;export TOPSRCDIR=$SRC_DIR;$SRC_DIR/nc_test4/run_par_test.sh"
140: Test timeout computed to be: 4800
140: 
140: Testing MPI parallel I/O with various other mode flags...
140: 
140: *** Testing illegal mode combinations
140: *** Testing create + MPIO + fletcher32
140: *** Testing create + MPIO + deflation
140: ok.
140: *** Tests successful!
140: 
140: Testing MPI parallel I/O without netCDF...
140: 
140: *** Testing basic MPI file I/O.
140: *** testing file create with parallel I/O with MPI...ok.
140: *** Tests successful!
140: 
140: Testing very simple parallel I/O with 4 processors...
140: 
140: *** tst_parallel testing very basic parallel access.
140: *** tst_parallel testing whether we can create file for parallel access and write to it...ok.
140: *** Tests successful!
140: 
140: Testing simple parallel I/O with 16 processors...
140: --------------------------------------------------------------------------
140: There are not enough slots available in the system to satisfy the 16
140: slots that were requested by the application:
140: 
140:   ./tst_parallel3
140: 
140: Either request fewer slots for your application, or make more slots
140: available for use.
140: 
140: A "slot" is the Open MPI term for an allocatable unit where we can
140: launch a process.  The number of slots available are defined by the
140: environment in which Open MPI processes are run:
140: 
140:   1. Hostfile, via "slots=N" clauses (N defaults to number of
140:      processor cores if not provided)
140:   2. The --host command line parameter, via a ":N" suffix on the
140:      hostname (N defaults to 1 if not provided)
140:   3. Resource manager (e.g., SLURM, PBS/Torque, LSF, etc.)
140:   4. If none of a hostfile, the --host command line parameter, or an
140:      RM is present, Open MPI defaults to the number of processor cores
140: 
140: In all the above cases, if you want Open MPI to default to the number
140: of hardware threads instead of the number of processor cores, use the
140: --use-hwthread-cpus option.
140: 
140: Alternatively, you can use the --oversubscribe option to ignore the
140: number of available slots when deciding the number of processes to
140: launch.
140: --------------------------------------------------------------------------
140/183 Test #140: nc_test4_run_par_test .................***Failed    0.93 sec

Testing MPI parallel I/O with various other mode flags...

*** Testing illegal mode combinations
*** Testing create + MPIO + fletcher32
*** Testing create + MPIO + deflation
ok.
*** Tests successful!

Testing MPI parallel I/O without netCDF...

*** Testing basic MPI file I/O.
*** testing file create with parallel I/O with MPI...ok.
*** Tests successful!

Testing very simple parallel I/O with 4 processors...

*** tst_parallel testing very basic parallel access.
*** tst_parallel testing whether we can create file for parallel access and write to it...ok.
*** Tests successful!

Testing simple parallel I/O with 16 processors...
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 16
slots that were requested by the application:

  ./tst_parallel3

Either request fewer slots for your application, or make more slots
available for use.

A "slot" is the Open MPI term for an allocatable unit where we can
launch a process.  The number of slots available are defined by the
environment in which Open MPI processes are run:

  1. Hostfile, via "slots=N" clauses (N defaults to number of
     processor cores if not provided)
  2. The --host command line parameter, via a ":N" suffix on the
     hostname (N defaults to 1 if not provided)
  3. Resource manager (e.g., SLURM, PBS/Torque, LSF, etc.)
  4. If none of a hostfile, the --host command line parameter, or an
     RM is present, Open MPI defaults to the number of processor cores

In all the above cases, if you want Open MPI to default to the number
of hardware threads instead of the number of processor cores, use the
--use-hwthread-cpus option.

Alternatively, you can use the --oversubscribe option to ignore the
number of available slots when deciding the number of processes to
launch.
--------------------------------------------------------------------------
```


Looks like we need to patch to not test with 16 slots :smile:

**Comment by annefou** [comment]
You mean we need to skip tests that require too many CPUs?

**Comment by ocefpaf** [comment]
> You mean we need to skip tests that require too many CPUs?

Yep. Looks like we can get away with up to 4 on Azure but 16 is definitely not available to us.

**Comment by bgruening** [comment]
xref: https://github.com/Unidata/netcdf-c/issues/932

TESTPROC seems interesting ...

**Comment by annefou** [comment]
> xref: [Unidata/netcdf-c#932](https://github.com/Unidata/netcdf-c/issues/932)
> 
> TESTPROC seems interesting ...

yes! Thanks!

I think we need to add
# allow oversubscribing with openmpi in make check
export OMPI_MCA_rmaps_base_oversubscribe=yes

in recipe/build.sh 

This is what is done for hdf5

**Comment by ocefpaf** [comment]
The new error is a segfault :-/

```
test 140
        Start 140: nc_test4_run_par_test

140: Test command: /bin/bash "-c" "export srcdir=$SRC_DIR/nc_test4;export TOPSRCDIR=$SRC_DIR;$SRC_DIR/nc_test4/run_par_test.sh"
140: Test timeout computed to be: 4800
140: 
140: Testing MPI parallel I/O with various other mode flags...
140: --------------------------------------------------------------------------
140: The value of the MCA parameter "plm_rsh_agent" was set to a path
140: that could not be found:
140: 
140:   plm_rsh_agent: ssh : rsh
140: 
140: Please either unset the parameter, or check that the path is correct
140: --------------------------------------------------------------------------
140: [8da5f71fc30a:16828] [[INVALID],INVALID] FORCE-TERMINATE AT Not found:-13 - error plm_rsh_component.c(327)
140: [8da5f71fc30a:16828] *** Process received signal ***
140: [8da5f71fc30a:16828] Signal: Segmentation fault (11)
140: [8da5f71fc30a:16828] Signal code: Address not mapped (1)
140: [8da5f71fc30a:16828] Failing at address: (nil)
140: [8da5f71fc30a:16828] [ 0] /lib64/libpthread.so.0(+0xf7e0)[0x7f18019ae7e0]
140: [8da5f71fc30a:16828] *** End of error message ***
140: $SRC_DIR/nc_test4/run_par_test.sh: line 11: 16828 Segmentation fault      (core dumped) mpiexec -n 1 ./tst_mode
140/183 Test #140: nc_test4_run_par_test .................***Failed    0.42 sec

Testing MPI parallel I/O with various other mode flags...
--------------------------------------------------------------------------
The value of the MCA parameter "plm_rsh_agent" was set to a path
that could not be found:

  plm_rsh_agent: ssh : rsh

Please either unset the parameter, or check that the path is correct
--------------------------------------------------------------------------
[8da5f71fc30a:16828] [[INVALID],INVALID] FORCE-TERMINATE AT Not found:-13 - error plm_rsh_component.c(327)
[8da5f71fc30a:16828] *** Process received signal ***
[8da5f71fc30a:16828] Signal: Segmentation fault (11)
[8da5f71fc30a:16828] Signal code: Address not mapped (1)
[8da5f71fc30a:16828] Failing at address: (nil)
[8da5f71fc30a:16828] [ 0] /lib64/libpthread.so.0(+0xf7e0)[0x7f18019ae7e0]
[8da5f71fc30a:16828] *** End of error message ***
$SRC_DIR/nc_test4/run_par_test.sh: line 11: 16828 Segmentation fault      (core dumped) mpiexec -n 1 ./tst_mode
```

Looks like is a problem with running `openmpi` with docker. I'll investigate more tomorrow. @minrk did you experience that with `hdf5`? Any advice for us here?

**Comment by annefou** [comment]
I see that there are a number of environment variables defined for running with openmpi in the hdf5 recipe (in recipe/mpiexec.sh):

```shell
#!/bin/bash
set -euo pipefail

if [[ "$mpi" == "mpich" ]]; then
    export HYDRA_LAUNCHER=fork
    mpiexec="mpiexec"
fi

if [[ "$mpi" == "openmpi" ]]; then
    export OMPI_MCA_btl=self,tcp
    export OMPI_MCA_plm=isolated
    export OMPI_MCA_rmaps_base_oversubscribe=yes
    export OMPI_MCA_btl_vader_single_copy_mechanism=none
    mpiexec="mpiexec --allow-run-as-root"
fi

# pipe stdout, stderr through cat to avoid O_NONBLOCK issues
$mpiexec $@ 2>&1 | cat
```

mpiexec.sh is then used for running the tests in recipe/build.sh:
```shell
recipe/build.sh:  make check RUNPARALLEL="${RECIPE_DIR}/mpiexec.sh -n 2"
```

Could it help?

**Comment by ocefpaf** [comment]
It is passing :tada: 

Note that I did not add `mpich`, only `openmpi`. I'll leave that to another PR.

**Pull request merged**
