### PR TITLE
Eliminate compiler optimization on ppc64le

### PR DESCRIPTION
**Pull request by dopplershift**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Based on feedback, testing if this fixes the tests on ppc64le.

cc @WardF

### CODE REVIEW

**Comment by dopplershift** [comment]
Ok, pulled in @isuruf 's fixes for cmake from b899096 in #118.

**Comment by dopplershift** [comment]
@ocefpaf Can you give this a quick look?  I wasn't planning on bumping the build # since we don't have any builds for ppc64le for 4.8.0 yet?

**Comment by ocefpaf** [comment]
LGTM but why not making these changes in #118 since that one adds the zip support and bumps the build? Just want to avoid extra artifact b/c and possible hash changes that could create a new package with a different hash anyway.

**Comment by dopplershift** [comment]
Separation of concerns? It seemed like this was a way to plug only the failing build, but I forgot about the hashing issue. I'll squash together my changes and put on #118 when I get a chance (unless someone beats me to it).

**Comment by isuruf** [comment]
I'd like it if the changes from https://github.com/conda-forge/libnetcdf-feedstock/pull/118/commits/b899096d80676e592786f9d2e8246e0f53bcba82 was kept here with git author info.

**Comment by ocefpaf** [comment]
> I'd like it if the changes from [b899096](https://github.com/conda-forge/libnetcdf-feedstock/commit/b899096d80676e592786f9d2e8246e0f53bcba82) was kept here with git author info.


Do you want to do that here? I was not going to pull all the changes to be honest. I don't understand all of those and how they fit with the changes here.

**Comment by ocefpaf** [comment]
> I'd like it if the changes from [b899096](https://github.com/conda-forge/libnetcdf-feedstock/commit/b899096d80676e592786f9d2e8246e0f53bcba82) was kept here with git author info.

OK. I removed the only change from that commit. We do want those but I cannot address it right now and we really need to ship this netcdf version. @isuruf I'll close #118 once we merge it but feel free to either re-open it or to resubmit the changes. If you don't get to it I'll try it next week.

**Comment by isuruf** [comment]
There were more changes adapted here though.

**Comment by ocefpaf** [comment]
> There were more changes adapted here though.

From my commits?

**Comment by isuruf** [comment]
Nope. @dopplershift's commit 356944194cd2329ae43d095cb2534b532c20ae2c

**Comment by isuruf** [comment]
I pushed @dopplershift's commits from here to #118

**Comment by ocefpaf** [comment]
That better. Let's close this one and work on finishing #118. Thanks!

**Pull request closed without merging**
