### PR TITLE
Disable excessive logging

### LINKED ISSUE #77: Debug messages spamming my logs
Issue:

I desperately need debugging to be disabled. My logs get spammed with useless debug info every time I write a netCDF file to disk (via xarray) regardless of how my Python logger is configured. I have an order of magnitude more netCDF spam than real logs.

I see that #73 has been pending since March. I raise this issue so that you all know this is effecting users. In that issue, I see that we are changing the `./configure` flags for `-DCMAKE_C_FLAGS_{RELEASE,DEBUG}`. Couldn't we just set `-DENABLE_LOGGING=OFF` instead? Or just remove that option?

Also see NCAR/pynio#32.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /usr/local/miniconda3/envs/apollo:
#
# Name                    Version                   Build  Channel
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
apollo                    0.1.0.dev1                dev_0    <develop>
appnope                   0.1.0                 py37_1000    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
beautifulsoup4            4.7.1                 py37_1001    conda-forge
blosc                     1.16.3               h0a44026_0    conda-forge
bokeh                     1.1.0                    py37_0    conda-forge
boost-cpp                 1.68.0            h6f8c590_1000    conda-forge
bzip2                     1.0.6             h1de35cc_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cairo                     1.16.0            h9247486_1000    conda-forge
cartopy                   0.17.0          py37h929c6f0_1004    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cffi                      1.12.3           py37hccf1714_0    conda-forge
cftime                    1.0.3.4         py37h917ab60_1000    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               1.0.0                      py_0    conda-forge
cryptography              2.6.1            py37h212c5bf_0    conda-forge
curl                      7.64.1               h22ea746_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.9.0.1          py37h470a237_1    conda-forge
dask                      1.2.2                      py_0    conda-forge
dask-core                 1.2.2                      py_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
distributed               1.28.1                   py37_0    conda-forge
docutils                  0.14                  py37_1001    conda-forge
ephem                     3.7.6.0         py37h1de35cc_1001    conda-forge
expat                     2.2.5             h0a44026_1002    conda-forge
fontconfig                2.13.1            h1027ab8_1000    conda-forge
freetype                  2.10.0               h24853df_0    conda-forge
freexl                    1.0.5             h1de35cc_1002    conda-forge
g2clib                    1.6.0                h4e57d6e_9    conda-forge
geos                      3.7.1             h0a44026_1000    conda-forge
geotiff                   1.4.3             hce09ea4_1000    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
giflib                    5.1.7                h01d97ff_1    conda-forge
glib                      2.58.3            h2836805_1001    conda-forge
hdf4                      4.2.13            hf3c6af0_1002    conda-forge
hdf5                      1.10.4          nompi_h0cbb7df_1106    conda-forge
hdfeos2                   2.20              h207910d_1000    conda-forge
hdfeos5                   5.1.16               he536a34_4    conda-forge
heapdict                  1.0.0                 py37_1000    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
ipython                   7.5.0            py37h24bf2e0_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jasper                    1.900.1           h636a363_1006    conda-forge
jedi                      0.13.3                   py37_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
json-c                    0.13.1            h1de35cc_1001    conda-forge
kealib                    1.4.10            hecf890f_1003    conda-forge
kiwisolver                1.0.1           py37h04f5b5a_1002    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
libblas                   3.8.0                5_openblas    conda-forge
libcblas                  3.8.0                5_openblas    conda-forge
libcurl                   7.64.1               h16faf7d_0    conda-forge
libcxx                    8.0.0                         2    conda-forge
libcxxabi                 8.0.0                         2    conda-forge
libdap4                   3.19.1            hae55d67_1000    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgdal                   2.4.1                h16bfee5_0    conda-forge
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
libkml                    1.3.0             h71ee1b2_1009    conda-forge
liblapack                 3.8.0                5_openblas    conda-forge
libnetcdf                 4.6.2             h6b88ef6_1001    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libpq                     11.2                 h56406e1_1    conda-forge
libprotobuf               3.7.1                hfbae3c0_0    conda-forge
libspatialite             4.3.0a            h0cd9627_1026    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.0.10            h79f4b77_1001    conda-forge
libuuid                   2.32.1            h1de35cc_1000    conda-forge
libxgboost                0.82                 h6de7cb9_0    conda-forge
libxml2                   2.9.9                hd80cff7_0    conda-forge
libxslt                   1.1.32            h33a18ac_1002    conda-forge
llvm-openmp               8.0.0                h770b8ee_0    conda-forge
llvmlite                  0.25.0          py37h3fea490_1001    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.3.3            py37h08abf6f_0    conda-forge
markupsafe                1.1.1            py37h1de35cc_0    conda-forge
matplotlib                3.0.3                    py37_1    conda-forge
matplotlib-base           3.0.3            py37habd5b94_1    conda-forge
mock                      2.0.0                 py37_1001    conda-forge
msgpack-python            0.6.1            py37h04f5b5a_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
netcdf4                   1.5.1.2          py37h58b02fa_0    conda-forge
numba                     0.40.1          py37h1702cab_1000    conda-forge
numexpr                   2.6.9           py37h1702cab_1000    conda-forge
numpy                     1.16.3           py37hdf140aa_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.5             h436c29b_1001    conda-forge
openjpeg                  2.3.1                hc1feee7_0    conda-forge
openssl                   1.1.1b               h01d97ff_2    conda-forge
owslib                    0.17.1                     py_0    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.2           py37h0a44026_0    conda-forge
parso                     0.4.0                      py_0    conda-forge
partd                     0.3.9                      py_0    conda-forge
pbr                       5.1.3                      py_0    conda-forge
pcre                      8.41              h0a44026_1003    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    6.0.0            py37h7095ceb_0    conda-forge
pip                       19.0.3                   py37_0    conda-forge
pixman                    0.34.0            h1de35cc_1003    conda-forge
poppler                   0.67.0               hb974355_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.2                 hf10c77c_1    conda-forge
proj4                     5.2.0             h1de35cc_1001    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
protobuf                  3.7.1            py37h6de7cb9_0    conda-forge
psutil                    5.6.2            py37h01d97ff_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pvlib-python              0.6.1                      py_0    conda-forge
py-xgboost                0.82             py37h6de7cb9_0    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pykdtree                  1.3.1           py37h917ab60_1002    conda-forge
pynio                     1.5.5            py37h7b68eac_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyproj                    1.9.6           py37h9c430a6_1000    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.6.8                 py37_1002    conda-forge
pytables                  3.5.1            py37h689b3ec_1    conda-forge
python                    3.7.3                h0d93f26_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
pyyaml                    5.1              py37h1de35cc_0    conda-forge
readline                  7.0               hcfe32e1_1001    conda-forge
requests                  2.21.0                py37_1000    conda-forge
scikit-learn              0.20.3           py37hca23c92_1    conda-forge
scipy                     1.2.1            py37hbd7caa9_1    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
shapely                   1.6.4           py37h4b8df73_1003    conda-forge
siphon                    0.8.0                 py37_1001    conda-forge
six                       1.12.0                py37_1000    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
soupsieve                 1.9.1                    py37_0    conda-forge
sphinx                    2.0.1                      py_0    conda-forge
sphinx_rtd_theme          0.4.3                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.1                      py_0    conda-forge
sqlite                    3.26.0            h1765d9f_1001    conda-forge
tblib                     1.3.2                      py_1    conda-forge
tk                        8.6.9             ha441bb4_1001    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   6.0.2            py37h01d97ff_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
tzcode                    2018g             h1de35cc_1001    conda-forge
urllib3                   1.24.2                   py37_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
wheel                     0.33.1                   py37_0    conda-forge
xarray                    0.12.1                     py_0    conda-forge
xerces-c                  3.2.2             h44e365a_1001    conda-forge
xgboost                   0.82             py37h6de7cb9_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.1.7             h1de35cc_1001    conda-forge
zict                      0.1.4                      py_0    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : apollo
    active env location : /usr/local/miniconda3/envs/apollo
            shell level : 2
       user config file : /Users/csb/.condarc
 populated config files : /Users/csb/.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.6.7.final.0
       base environment : /usr/local/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/pytorch/osx-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/miniconda3/pkgs
                          /Users/csb/.conda/pkgs
       envs directories : /usr/local/miniconda3/envs
                          /Users/csb/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.6.7 Darwin/18.6.0 OSX/10.14.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```
</details>

### PR DESCRIPTION
**Pull request by cbarrick**
This PR removes the option `-DENABLE_LOGGING=ON` from the call to `cmake`.

The purpose of this PR is to remove the excessive logging spewed by netCDF related packages. This closes #77.

I have also backported this patch to v4.6.1 and v4.6.2, based on the the v4.6.1 branch and commit 56e186f respectively. I can make a PR against the v4.6.1 branch, but there is no v4.6.2 branch to make a PR there. I would very much like to see a release with this patch for v4.6.2.

This PR does _not_ pass the tests on my machine (macOS 10.14). I trying to dig into which test is failing, but my knowledge here is weak. The `conda build` logs give zero indication. I can post the relevant section if necessary. (**Edited**)

When testing this package in my downstream application, everything seems to work.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by cbarrick** [comment]
I'm not sure if those last two points in the checklist are applicable or what I should do to make progress there. I don't have much experience contributing to conda-forge.

**Comment by kmuehlbauer** [comment]
@conda-forge-admin, please rerender

**Comment by kmuehlbauer** [comment]
@cbarrick Thanks for looking into this. Let's see what/if the rerendering changes something.

**Comment by kmuehlbauer** [comment]
The last checkbox does not apply here, the license file is already available.

**Comment by cbarrick** [comment]
I see the failing test now:

    nc-config --has-logging  | grep -q yes

That was way too obvious. I'm surprised I missed it. I'll update my patch.

This test will obviously fail when logging is disabled. What is the reason that this is a test? Are there other packages/users that depend on this?

**Comment by kmuehlbauer** [comment]
@cbarrick I have problems accessing the failing azure logs (on the phone). Are you seeing the same errors you experienced locally?

**Comment by kmuehlbauer** [comment]
@cbarrick I've no idea about that logging test. We should remove it, then. I hope that others chime in, if this is needed.

**Comment by kmuehlbauer** [comment]
@cbarrick I've digged up this:

**Comment by kmuehlbauer** [comment]
Ping @WardF: If logging enabled, can the output be silenced somehow? Or is this either/or?

**Comment by cbarrick** [comment]
I've updated the patch and have the tests passing for me locally.

FWIW, yes the Azure logs were the same as what I was seeing. There's nothing helpful there though. Just a generic error: `Tests failed for libnetcdf-4.6.3-h66079b2_1.tar.bz2`. Here's the relevant section:

```console
TEST START: /usr/local/miniconda/conda-bld/osx-64/libnetcdf-4.6.3-h66079b2_1.tar.bz2
Renaming work directory,  /usr/local/miniconda/conda-bld/libnetcdf_1558028763243/work  to  /usr/local/miniconda/conda-bld/libnetcdf_1558028763243/work_moved_libnetcdf-4.6.3-h66079b2_1_osx-64
Collecting package metadata: ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /usr/local/miniconda/conda-bld/libnetcdf_1558028763243/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_


The following NEW packages will be INSTALLED:

    bzip2:           1.0.6-h1de35cc_1002        conda-forge
    ca-certificates: 2019.3.9-hecc5488_0        conda-forge
    curl:            7.64.1-h22ea746_0          conda-forge
    hdf4:            4.2.13-hf3c6af0_1002       conda-forge
    hdf5:            1.10.4-nompi_h0cbb7df_1106 conda-forge
    jpeg:            9c-h1de35cc_1001           conda-forge
    krb5:            1.16.3-hcfa6398_1001       conda-forge
    libcurl:         7.64.1-h16faf7d_0          conda-forge
    libcxx:          8.0.0-2                    conda-forge
    libcxxabi:       8.0.0-2                    conda-forge
    libedit:         3.1.20170329-hcfe32e1_1001 conda-forge
    libgfortran:     3.0.1-0                    conda-forge
    libnetcdf:       4.6.3-h66079b2_1           local      
    libssh2:         1.8.2-hcdc9a53_2           conda-forge
    ncurses:         6.1-h0a44026_1002          conda-forge
    openssl:         1.1.1b-h01d97ff_2          conda-forge
    tk:              8.6.9-ha441bb4_1001        conda-forge
    zlib:            1.2.11-h1de35cc_1004       conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
WARNING: symlink_conda() is deprecated.
export PREFIX=/usr/local/miniconda/conda-bld/libnetcdf_1558028763243/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
export SRC_DIR=/usr/local/miniconda/conda-bld/libnetcdf_1558028763243/test_tmp
Tests failed for libnetcdf-4.6.3-h66079b2_1.tar.bz2 - moving package to /usr/local/miniconda/conda-bld/broken
WARNING:conda_build.build:Tests failed for libnetcdf-4.6.3-h66079b2_1.tar.bz2 - moving package to /usr/local/miniconda/conda-bld/broken
TESTS FAILED: libnetcdf-4.6.3-h66079b2_1.tar.bz2
```

**Comment by cbarrick** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
> This test will obviously fail when logging is disabled. What is the reason that this is a test? Are there other packages/users that depend on this?

I do not recall why logging was added in the first place. Let's remove it and, if people need it, we can try to create a variant package for it.

**Comment by kmuehlbauer** [comment]
Thanks @cbarrick !

**Pull request merged**
