### PR TITLE
Bump

### PR DESCRIPTION
**Pull request by ocefpaf**
```
## 4.4.1 - June 28, 2016

* [File Change] Starting with release 4.4.1, netCDF-4 files created will have superblock version 0 instead of superblock version 2, as was observed in previous netCDF versions.  This is due to a workaround required to avoid backwards binary incompatibility when using libhdf5 1.10.x or greater.  Superblock versions 0 and 2 appear to be forward and backward compatible.  Other than a different superblock number the data should remain consistent.
* [Enhancement] Added better error reporting when ncdump/nccopy are given a bad constraint in a DAP url. See [GitHub #279](https://github.com/Unidata/netcdf-c/pull/279) for more information.

### 4.4.1-RC3 - June 17, 2016

* [Bug Fix] Misc. bug fixes and improvements.
* [Bug Fix] Corrected an issue where adding a \_FillValue attribute to a variable would result in other attributes being lost. See [GitHub #239](https://github.com/Unidata/netcdf-c/issues/239) for more details.
* [Bug Fix][Parallel I/O] Corrected an issue reported by Kent Yang at the HDF group related to Collective Parallel I/O and a potential hang.

### 4.4.1-RC2 - May 13, 2016

* [Enhancement] Added provenance information to files created.  This information consists of a persistent attribute named `_NCProperties` plus two computed attributes, `_IsNetcdf4` and `_SuperblockVersion`.  Associated documentation was added to the file `docs/attribute_conventions.md`.  See [GitHub pull request #260](https://github.com/Unidata/netcdf-c/pull/260) for more information.
* [Bug Fix] Cleaned up some dead links in the doxygen-generated documentation.
* [Bug Fix] Corrected several issues related to building under Visual Studio 2014.
* [Bug Fix] Corrected several test failures related to HDF5 `1.10.0`
* [Bug Fix] Reverted SOVersion *current* to 11 from 12; it was incorrectly incremented in netCDF-C release 4.4.1-RC1.
* [Enhancement][Windows] Bumped the included libhdf5 to 1.8.16 from 1.8.15 for pre-built Visual Studio installer files.


### 4.4.1-RC1 - April 15, 2016

* [Bug Fix][Enhancement] Fixed an issue with netCDF4 files generated using version `1.10.0` of the HDF5 library.  The 1.10 release potentially changed the underlying file format, introducing a backwards compatibility issue with the files generated.  HDF5 provided an API for retaining the 1.8.x file format, which is now on by default.  See [GitHub Issue #250](https://github.com/Unidata/netcdf-c/issues/250) for more information.
* [Bug Fix] Corrected an issue with autotools-based builds performed out-of-source-tree.  See [GitHub Issue #242](https://github.com/Unidata/netcdf-c/issues/242) for more information.
* [Enhancement] Modified `nc_inq_type()` so that it would work more broadly without requiring a valid ncid.  See [GitHub Issue #240](https://github.com/Unidata/netcdf-c/issues/240) for more information.
* [Enhancement] Accepted a patch code which added a hashmap lookup for rapid var and dim retrieval in nc3 files, contributed by Greg Sjaardema.  See [GitHub Pull Request #238](https://github.com/Unidata/netcdf-c/pull/238) for more information.
* [Bug Fix] Accepted a contributed pull request which corrected an issue with how the cmake-generated `nc-config` file determined the location of installed files. See [GitHub Pull Request #235](https://github.com/Unidata/netcdf-c/pull/235) for more information.
* [Enhancement] Added an advanced option for CMake-based builds, `ENABLE_SHARED_LIBRARY_VERSION`.  This option is `ON` by default, but if turned off, only `libnetcdf.dylib` will be generated, instead of files containing the SOVERSION in the file name.  This is a requested feature most people might not care about.  See [GitHub #228](https://github.com/Unidata/netcdf-c/issues/228) for more information.
* [Bug Fix] Corrected an issue with duplicated error codes defined in multiple header files.  See [GitHub #213](https://github.com/Unidata/netcdf-c/issues/213) for more information.
* [Bug Fix] Addressed an issue specific to Visual Studio 2015 on Windows.  On very large files, some calls to the `fstat` class of functions would fail for no apparent reason. This behavior was **not** observed under Visual Studio 2013. This has now been mitigated.  See [GitHub #188](https://github.com/Unidata/netcdf-c/issues/188) for more information.
* [Enhancement] Updated `nc-config` to report whether `logging` is enabled in netcdf.  Additionally, if `f03` is available in an installed netcdf-fortran library, it will now be reported as well.
* [Bug Fix] Addressed an issue where `netcdf_mem.h` was not being installed by cmake. See [GitHub #227](https://github.com/Unidata/netcdf-c/issues/227) for more information.
* [Bug Fix] Addressed an issue where `ncdump` would crash when trying to read a netcdf file containing an empty ragged `VLEN` variable in an unlimited dimension. See [GitHub #221](https://github.com/Unidata/netcdf-c/issues/221) for more information.
```

### CODE REVIEW

**Comment by ocefpaf** [comment]
@WardF I had to use `ENABLE_TESTS=OFF` due to:

```shell
-- Configuring done
CMake Error at nc_test/CMakeLists.txt:18 (ADD_EXECUTABLE):
  Cannot find source file:

    test_get.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: nc_test
CMake Error: Cannot determine link language for target "nc_test".
```

not sure if I am doing something wrong or if the latest cmake files are missing something.

**Comment by ocefpaf** [comment]
@gillins can you take a look at the Windows errors here? Only `PY35` is passing.

```shell
-- Build files have been written to: C:/conda/conda-bld/work/netcdf-c-4.4.1/build
(C:\conda\envs\_build) C:\conda\conda-bld\work\netcdf-c-4.4.1\build>if errorlevel 1 exit 1 
(C:\conda\envs\_build) C:\conda\conda-bld\work\netcdf-c-4.4.1\build>nmake
Microsoft (R) Program Maintenance Utility Version 10.00.40219.01
Copyright (C) Microsoft Corporation.  All rights reserved.
Scanning dependencies of target dispatch
[  0%] Building C object libdispatch/CMakeFiles/dispatch.dir/dparallel.c.obj
dparallel.c
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\sys/stat.inl(52) : warning C4028: formal parameter 2 different from declaration
[  1%] Building C object libdispatch/CMakeFiles/dispatch.dir/dcopy.c.obj
dcopy.c
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\sys/stat.inl(52) : warning C4028: formal parameter 2 different from declaration
[  1%] Building C object libdispatch/CMakeFiles/dispatch.dir/dfile.c.obj
dfile.c
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\sys/stat.inl(52) : warning C4028: formal parameter 2 different from declaration
C:\conda\conda-bld\work\netcdf-c-4.4.1\libdispatch\dfile.c(185) : error C2143: syntax error : missing ';' before 'type'
C:\conda\conda-bld\work\netcdf-c-4.4.1\libdispatch\dfile.c(186) : error C2065: 'file_len' : undeclared identifier
C:\conda\conda-bld\work\netcdf-c-4.4.1\libdispatch\dfile.c(192) : error C2065: 'file_len' : undeclared identifier
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~2.0\VC\bin\amd64\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Bin\amd64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Bin\amd64\nmake.exe"' : return code '0x2'
Stop.
(C:\conda\envs\_build) C:\conda\conda-bld\work\netcdf-c-4.4.1\build>if errorlevel 1 exit 1 
Command failed: C:\windows\system32\cmd.exe /c bld.bat
```

I wonder if we should start abandoning `Python < 3.5` in some `feedstocks`...

**Comment by gillins** [comment]
:+1: to dropping `Python < 3.5` and :+1: :+1: to using `mingy/gcc` :smile: 

I've sent you a PR (I think)

**Comment by ocefpaf** [comment]
> :+1: to dropping `Python < 3.5` and :+1: :+1: to using `mingy/gcc` :smile: 

`defaults` has `msys2` now. Maybe it is worth a try. Not sure what it takes to switch to it though.

> I've sent you a PR (I think)

It worked! Thanks!! Waiting for AppVeyor now...

**Pull request merged**
